// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AboutSection } from "./AboutSection";
import type { AppLinks } from "./AppLinks";
import type { SeoBlock } from "./SeoBlock";
import type { StatTile } from "./StatTile";

/**
 * About ページ (`/about/`)。
 */
export type AboutPage = { schemaVersion: number, path: string, 
/**
 * 件数タイル (トップの 6 種 + セトリ項目)。押せるリンクは持たない。
 */
statTiles: Array<StatTile>, dataVersion: string | null, contentHash: string | null, generatedAt: string, todayJst: string, app: AppLinks, 
/**
 * 版権・ライセンス・歌詞などの固定文。見出しと本文の対で持つ。
 */
sections: Array<AboutSection>, seo: SeoBlock, };
