// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AboutSection } from "./AboutSection";
import type { AppLinks } from "./AppLinks";
import type { Counts } from "./Counts";
import type { SeoBlock } from "./SeoBlock";

/**
 * About ページ (`/about/`)。
 */
export type AboutPage = { schemaVersion: number, path: string, counts: Counts, dataVersion: string | null, contentHash: string | null, generatedAt: string, todayJst: string, app: AppLinks, 
/**
 * 版権・ライセンス・歌詞などの固定文。見出しと本文の対で持つ。
 */
sections: Array<AboutSection>, seo: SeoBlock, };
