// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AboutLink } from "./AboutLink";

/**
 * About の 1 節。
 */
export type AboutSection = { heading: string, 
/**
 * 段落の列 (1 段落 1 要素)。
 */
paragraphs: Array<string>, links: Array<AboutLink>, };
