// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * About から外に出るリンク。
 */
export type AboutLink = { label: string, href: string, 
/**
 * 外部サイトか (`rel="noopener"` と外部アイコンの材料)。
 */
external: boolean, };
