// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * アプリ / 外部サイトへのリンク集。値の正はこの 1 箇所だけ。
 */
export type AppLinks = { appStoreUrl: string, 
/**
 * Google Play は 2026-09-04 時点で 404 のため `None`。出面にリンクを出さない。
 */
playStoreUrl: string | null, hashtag: string, privacyUrl: string, supportUrl: string, termsUrl: string, repositoryUrl: string, };
