// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 「アプリで開く」導線。
 *
 * Web は閲覧専用なので、状態を持つ操作 (参加記録・投票・タグ・歌詞・コール) は
 * すべてここからアプリへ送る。
 */
export type AppOpen = { appStoreUrl: string, 
/**
 * `imaslivedb://events/<id>` 等。**event / show にしか無い**
 * (`DeeplinkRouter` が受けるのは events / shows / polls の 3 種だけ)。
 */
deeplink: string | null, 
/**
 * 「参加記録・投票・歌詞・タグはアプリで」等の固定文。
 */
note: string, };
