// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Counts } from "./Counts";
import type { Ref } from "./Ref";

/**
 * ブランド一覧の 1 行。
 */
export type BrandListItem = { ref: Ref, shortName: string | null, counts: Counts, };
