// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BrandListItem } from "./BrandListItem";
import type { SeoBlock } from "./SeoBlock";

/**
 * ブランド一覧ページ (`/brands/`)。
 */
export type BrandListPage = { schemaVersion: number, path: string, title: string, items: Array<BrandListItem>, seo: SeoBlock, };
