// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Counts } from "./Counts";
import type { NavLink } from "./NavLink";
import type { Ref } from "./Ref";
import type { SeoBlock } from "./SeoBlock";

/**
 * `/brands/<id>/` の中身。
 */
export type BrandPage = { schemaVersion: number, id: string, path: string, name: string, shortName: string | null, color: string | null, themeKey: string, 
/**
 * このブランドに属する件数だけを数えたもの。
 */
counts: Counts, idols: Array<Ref>, units: Array<Ref>, recentEvents: Array<Ref>, topSongs: Array<Ref>, 
/**
 * 「このブランドのライブ一覧へ」等の入口。
 */
sectionLinks: Array<NavLink>, seo: SeoBlock, };
