// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NavLink } from "./NavLink";
import type { Ref } from "./Ref";
import type { SeoBlock } from "./SeoBlock";
import type { StatTile } from "./StatTile";

/**
 * `/brands/<id>/` の中身。
 */
export type BrandPage = { schemaVersion: number, id: string, path: string, name: string, shortName: string | null, themeKey: string, 
/**
 * このブランドに属する件数のタイル (ライブ / 楽曲 / アイドル / ユニット)。
 *
 * 素の `Counts` を配らないのは、ブランドに紐付かない件数 (会場・セトリ項目) を
 * 0 で埋めて「web 側がそこを読まない」という口約束に頼る形になるため。
 * 意味のあるタイルだけを組んで渡す。
 */
statTiles: Array<StatTile>, idols: Array<Ref>, units: Array<Ref>, recentEvents: Array<Ref>, topSongs: Array<Ref>, 
/**
 * 「このブランドのライブ一覧へ」等の入口。
 */
sectionLinks: Array<NavLink>, seo: SeoBlock, };
