// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NavLink } from "./NavLink";
import type { Ref } from "./Ref";
import type { SeoBlock } from "./SeoBlock";

/**
 * `/brands/<id>/` の中身。
 */
export type BrandPage = { schemaVersion: number, id: string, path: string, name: string, shortName: string | null, themeKey: string, 
/**
 * そのブランドの一覧への入口 (ライブ / 楽曲 / アイドル / ユニット)。件数付き。
 *
 * 件数タイルを別に持たないのは、ヒーロー直下 100px の間に同じ数字が 2 回
 * 出ていたため。押せるこちらだけを残す。**一覧を作っていない組み合わせは
 * そもそも並ばない** (`other` はアイドルだけ) ので、リンク切れにならない。
 */
sectionLinks: Array<NavLink>, idols: Array<Ref>, units: Array<Ref>, recentEvents: Array<Ref>, topSongs: Array<Ref>, seo: SeoBlock, };
