// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CalendarItemKind } from "./CalendarItemKind";
import type { Ref } from "./Ref";

/**
 * 予定 1 件。
 */
export type CalendarItem = { kind: CalendarItemKind, 
/**
 * 「公演」「リリース」「誕生日」「記念日」「申込締切」…。語は `content::CALENDAR_KIND_*`。
 */
kindLabel: string, label: string, sub: string | null, 
/**
 * 押し先 (公演・アイドル・ライブ・ブランド)。無いものは押せない。
 */
path: string | null, 
/**
 * 色 (ブランド / アイドル / neutral)。
 */
themeKey: string, 
/**
 * リリースの日だけ: その日に出た曲。
 */
refs: Array<Ref>, };
