// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CalendarDayGroup } from "./CalendarDayGroup";
import type { CalendarWeek } from "./CalendarWeek";
import type { FilterAxis } from "./FilterAxis";
import type { NavLink } from "./NavLink";
import type { SeoBlock } from "./SeoBlock";

/**
 * 月のカレンダー 1 枚。
 */
export type CalendarPage = { schemaVersion: number, path: string, 
/**
 * `2026年9月`。
 */
title: string, 
/**
 * この月の件数を 1 行に (`公演 10 ・ リリース曲 35 ・ 誕生日 32`)。0 のものは無く、全部 0 なら `None`。
 */
summary: string | null, 
/**
 * 前の月・次の月。範囲の端では `None`。
 */
prev: NavLink | null, next: NavLink | null, 
/**
 * 今月へ戻る導線。今月のページ自身には無い。
 */
todayLink: NavLink | null, 
/**
 * 年 (範囲内の年だけ、新しい順。押すとその年の最初の月) と、同じ年の月 (範囲外の月は無い) の切替。
 */
filters: Array<FilterAxis>, 
/**
 * 曜日の見出し (日曜始まり、アプリと同じ)。
 */
weekdayLabels: Array<string>, 
/**
 * 週ごとの 7 日。月の外の日も枠を揃えるために入る (`in_month = false`)。
 */
weeks: Array<CalendarWeek>, 
/**
 * 予定のある日だけを日付順に (枠の下に並べる一覧)。
 */
days: Array<CalendarDayGroup>, seo: SeoBlock, };
