// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 日を跨ぐ帯の 1 日ぶん。
 */
export type CalendarBand = { label: string, themeKey: string, 
/**
 * この日が帯の始まり / 終わりか (角を丸める材料)。
 */
starts: boolean, ends: boolean, path: string | null, };
