// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CalendarDayGroup } from "./CalendarDayGroup";
import type { CalendarWeek } from "./CalendarWeek";
import type { NavLink } from "./NavLink";
import type { SeoBlock } from "./SeoBlock";
import type { StatTile } from "./StatTile";

/**
 * 月のカレンダー 1 枚。
 */
export type CalendarPage = { schemaVersion: number, path: string, 
/**
 * `2026年9月`。
 */
title: string, 
/**
 * `2026-09`。
 */
monthKey: string, lede: string, 
/**
 * この月の件数 (公演・リリース曲・誕生日・記念日)。0 のものは無い。
 */
statTiles: Array<StatTile>, 
/**
 * 前の月・次の月。範囲の端では `None`。
 */
prev: NavLink | null, next: NavLink | null, 
/**
 * 今月へ戻る導線。今月のページ自身には無い。
 */
todayLink: NavLink | null, 
/**
 * 年の切替 (範囲内の年だけ。押すとその年の最初の月)。
 */
yearLinks: Array<NavLink>, 
/**
 * 同じ年の月の切替 (範囲外の月は無い)。
 */
monthLinks: Array<NavLink>, 
/**
 * 曜日の見出し (日曜始まり、アプリと同じ)。
 */
weekdayLabels: Array<string>, 
/**
 * 週ごとの 7 日。月の外の日も枠を揃えるために入る (`in_month = false`)。
 */
weeks: Array<CalendarWeek>, 
/**
 * 予定のある日だけを日付順に (枠の下に並べる一覧)。
 */
days: Array<CalendarDayGroup>, seo: SeoBlock, };
