// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CalendarBand } from "./CalendarBand";
import type { CalendarItem } from "./CalendarItem";

/**
 * 枠の 1 日。
 */
export type CalendarDay = { 
/**
 * `2026-09-06`。下の一覧の見出しの id にもなる。
 */
date: string, day: number, inMonth: boolean, isToday: boolean, 
/**
 * 0 = 日曜 … 6 = 土曜。
 */
weekday: number, 
/**
 * 枠に出す分 (先頭の数件)。全部は [`CalendarDayGroup::items`]。月の外の日は空。
 */
items: Array<CalendarItem>, 
/**
 * 枠に入り切らなかった件数の札 (`+2`)。
 */
overflowLabel: string | null, 
/**
 * 日を跨ぐ帯 (チケット受付期間)。
 */
bands: Array<CalendarBand>, };
