// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CalendarItem } from "./CalendarItem";
import type { DateBadge } from "./DateBadge";

/**
 * 予定のある 1 日 (枠の下の一覧)。
 */
export type CalendarDayGroup = { dateBadge: DateBadge, items: Array<CalendarItem>, };
