// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ref } from "./Ref";

/**
 * コールガイドがある曲 1 行。
 */
export type CallGuideSongRow = { song: Ref, 
/**
 * `32 件・19 行`。
 */
detail: string, 
/**
 * `2026-09-05 (金)`。
 */
updatedDisplay: string, 
/**
 * マスク済みの表示名 (無ければ `匿名`、Worker が決める)。
 */
updatedBy: string, };
