// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * コールの強調度 1 種。凡例の語。色は出面の CSS が `kind` で引く。
 */
export type CallGuideEmphasis = { 
/**
 * Worker が返す `emphasis` の値 (`normal` / `optional` / `performer_request`)。
 */
kind: string, label: string, };
