// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 手拍子の指示 1 種。行頭に `symbol`、凡例に `label` を出す。
 */
export type CallGuideClap = { 
/**
 * Worker が返す `clap` の値 (`back_beat` / `four_on_floor` / `ppph` / `none`)。
 */
kind: string, symbol: string, label: string, };
