// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CallGuideClap } from "./CallGuideClap";
import type { CallGuideEmphasis } from "./CallGuideEmphasis";

/**
 * コールガイドの語彙。手拍子の記号・強調度の名前は アプリ (`Models/Lyrics.swift`) と同じ語を
 * Rust が配り、出面はアンカーの位置とこの語彙を突き合わせて置くだけ。
 *
 * 出面はコールを**位置で示す** (同時 = 語の真下 / 追っかけ = 語の後ろ) ので、
 * アプリの ↳ ①② » の印や「同時」札は持たない。
 */
export type CallGuideVocabulary = { claps: Array<CallGuideClap>, emphases: Array<CallGuideEmphasis>, 
/**
 * 歌詞が直されてアンカーがズレたコールの印 (`ズレ`)。
 */
staleLabel: string, };
