// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CallGuideClap } from "./CallGuideClap";
import type { CallGuideEmphasis } from "./CallGuideEmphasis";

/**
 * コールガイドの語彙。アプリ (`Models/Lyrics.swift` / `CallGuideLineViews.swift`) と同じ
 * 語・記号を Rust が配り、出面はアンカーの位置とこの語彙を突き合わせて置くだけ。
 */
export type CallGuideVocabulary = { claps: Array<CallGuideClap>, emphases: Array<CallGuideEmphasis>, 
/**
 * 行内の 1 箇所に掛かるコールの印 (`↳`)。
 */
markerSingle: string, 
/**
 * 掛かる範囲が無い (行末) コールの印 (`»`)。
 */
markerEnd: string, 
/**
 * 同じ行に複数のアンカーがあるときの対応付け (`①②③…`)。足りなければ受け手が素の数字に落とす。
 */
anchorMarkers: Array<string>, 
/**
 * 歌に被せるコールの札 (`同時`)。追っかけが既定なので被せる方だけ出す。
 */
timingOverLabel: string, 
/**
 * 範囲付きと混ざった行での行末コールの札 (`行末`)。
 */
endLabel: string, 
/**
 * 歌詞が直されてアンカーがズレたコールの印 (`ズレ`)。
 */
staleLabel: string, 
/**
 * 凡例で `同時` に添える説明 (`歌に被せる`)。
 */
legendOverLabel: string, };
