// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ref } from "./Ref";

/**
 * 最近の編集 1 件。
 */
export type CallGuideEditRow = { song: Ref, 
/**
 * `コールを付けた (32 件・19 行)` など。言い方は iOS と同じ規則。
 */
label: string, atDisplay: string, by: string, };
