// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CallGuideEditRow } from "./CallGuideEditRow";
import type { CallGuideSongRow } from "./CallGuideSongRow";
import type { EmptyText } from "./EmptyText";
import type { Ref } from "./Ref";
import type { SeoBlock } from "./SeoBlock";
import type { StatTile } from "./StatTile";

export type CallGuidePage = { schemaVersion: number, path: string, title: string, 
/**
 * 説明文 (iOS のダッシュボードと同じ)。
 */
intro: string, 
/**
 * `2026-09-06 12:34 (JST) 時点の情報です…`。写しの時刻は Worker の `generatedAt`。
 */
snapshotNote: string, 
/**
 * ガイドあり / 書き手募集中 / タグ付き の数。0 も出す (「未整備 0」は良い知らせ)。
 */
statTiles: Array<StatTile>, 
/**
 * コールガイドがある曲 (更新の新しい順)。
 */
withCalls: Array<CallGuideSongRow>, 
/**
 * ガイドのある曲が 1 曲も無いときの案内。
 */
withCallsEmpty: EmptyText | null, 
/**
 * 一覧が Worker の上限で打ち切られているときの断り。
 */
withCallsNote: string | null, 
/**
 * 最近の編集 (新しい順)。
 */
recentEdits: Array<CallGuideEditRow>, 
/**
 * 編集が 1 件も無いときの案内。
 */
recentEditsEmpty: EmptyText | null, 
/**
 * 書き手募集中の節の説明 (何の曲を・どの順で並べているか)。
 */
wantedLede: string, 
/**
 * 「コール曲」タグが付いているのに未整備の曲 (票の多い順)。
 */
wanted: Array<Ref>, 
/**
 * 未整備の曲が 1 曲も無いときの案内。
 */
wantedEmpty: EmptyText | null, 
/**
 * 見出しに添える断り (歌詞が未登録で並べていない曲数)。
 */
wantedNote: string | null, seo: SeoBlock, };
