// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ref } from "./Ref";
import type { SeoBlock } from "./SeoBlock";

export type CardCatalog = { schemaVersion: number, 
/**
 * 担当 (`oshi_idol_ids`) を解決するための全アイドル。
 */
idols: Array<Ref>, 
/**
 * 「次の現場」(`next_show_id`) を解決するための、今日以降の公演。
 */
upcomingShows: Array<Ref>, 
/**
 * 「アプリで開いて名刺入れに入れる」導線。
 */
appStoreUrl: string, 
/**
 * `<この値><#の後ろ>` でカスタムスキームの URL になる (`"imaslivedb://p#"`)。
 * 値そのものが名刺の読み取り (`decode_producer_card`) が認める prefix と同じもの。
 */
deeplinkPrefix: string, appOpenTitle: string, appOpenNote: string, 
/**
 * 読み解けない名刺のときに出す文面。
 */
unreadableText: string, 
/**
 * `/p/` の `<head>`。個人の名刺なので常に noindex
 * (`Robots::NoindexFollow`)。パンくず・JSON-LD は持たない
 * (どこにも位置しない、`404.html` と同じ扱い)。
 */
seo: SeoBlock, };
