// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 演者の種別 (`domain::event_detail_queries::PerformerKind` の写し)。
 */
export type CastKind = "voice" | "stage";
