// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ref } from "./Ref";

/**
 * 「よく一緒に披露される曲」の 1 行。
 */
export type CoOccurRow = { song: Ref, 
/**
 * 同じ公演に並んだ回数。
 */
together: number, 
/**
 * 相手の総披露回数。
 */
performances: number, };
