// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 残り日数の札 (`あと 2 日` / `今日`)。数字だけを大きく置けるよう 3 つに分ける。
 */
export type Countdown = { 
/**
 * 数字の前 (`あと`)。当日は空。
 */
lead: string, 
/**
 * 大きく置く部分 (`2` / `今日`)。
 */
value: string, 
/**
 * 数字の後 (`日`)。当日は空。
 */
unit: string, 
/**
 * 読み上げ用の 1 本 (`あと2日`)。
 */
spoken: string, };
