// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 各コレクションの件数。トップの統計タイルと `/about/` が使う。
 */
export type Counts = { events: number, shows: number, songs: number, idols: number, units: number, venues: number, brands: number, setlistItems: number, };
