// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 作詞 / 作曲 / 編曲 の 1 区分。
 */
export type CreditGroup = { 
/**
 * 「作詞」「作曲」「編曲」。
 */
role: string, 
/**
 * 分割前の自由文字列 (分割規則が拾えなかった表記もそのまま見せられるように)。
 */
raw: string, people: Array<string>, };
