// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 作詞 / 作曲 / 編曲 の 1 区分。
 */
export type CreditGroup = { 
/**
 * 「作詞」「作曲」「編曲」。
 */
role: string, 
/**
 * 1 行で出すときの表記。`credit_names::split_credits` で分けた名前を `" / "` で
 * 繋いだもので、分割規則が拾えなかった表記は元の自由文字列がそのまま入る。
 * **TS 側で join しない**ための項目 (区切り文字の判断もコアが持つ)。
 */
display: string, };
