// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 日付ブロック 1 つぶん (行の左端に置く「月日を大きく、曜日と年を小さく」の部品)。
 *
 * 文字列を切る・曜日を求める判断を受け手に持たせないための型。値の決め方は
 * `domain::date_display::date_parts` にあり、ここは詰め替えるだけ。
 * 部分日付 (`"2024-08"`) では `month_day` が `"8月"` で `weekday` が無い、
 * 解釈できない文字列では `month_day` に原文がそのまま入る (捏造しない)。
 */
export type DateBadge = { 
/**
 * `"2026-09-19"`。そのまま `<time datetime>` に入れる。
 */
iso: string, 
/**
 * `"2026"`。読めなければ空。
 */
year: string, 
/**
 * `"9/19"`。
 */
monthDay: string, 
/**
 * `"土"`。日まで揃った実在の日付にだけ入る。
 */
weekday: string | null, };
