// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 一覧・節が空のときの案内。**中身が空のときだけ入る** (中身があれば `None`)。
 *
 * 空かどうかも文言も JSON を作る側が決める。受け手は「あれば案内を出す」だけ。
 */
export type EmptyText = { title: string, body: string | null, };
