// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventListKind } from "./EventListKind";
import type { NavLink } from "./NavLink";
import type { SeoBlock } from "./SeoBlock";
import type { YearGroup } from "./YearGroup";

/**
 * ライブ一覧ページ。`/events/` `/events/upcoming/` `/events/past/`
 * `/events/past/<year>/` `/events/brand/<brandId>/` が同じ型を使う。
 */
export type EventListPage = { schemaVersion: number, path: string, title: string, kind: EventListKind, 
/**
 * `event_grouping::group_events_by_year` の結果をそのまま写したもの。
 */
groups: Array<YearGroup>, 
/**
 * 今後 / 開催済み の切替。
 */
scopeLinks: Array<NavLink>, brandLinks: Array<NavLink>, yearLinks: Array<NavLink>, total: number, seo: SeoBlock, };
