// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `event_detail_queries::event_stats` の写し。
 */
export type EventStats = { showCount: number, totalSongs: number, uniqueSongs: number, castCount: number, };
