// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateBadge } from "./DateBadge";
import type { Ref } from "./Ref";

/**
 * ライブ一覧の 1 行。
 *
 * 日付・ブランド・会場・公演数を**別々の項目**で持つ。行はそれぞれを別の位置
 * (日付ブロック / 色付きの札 / 文字 / 数) に置くので、1 本に繋いだ副題は持たない。
 * 何を出す・何を落とすの判断はすべてここまでで済んでいて、受け手は置くだけ。
 */
export type EventListItem = { ref: Ref, 
/**
 * 行の左端に置く日付ブロック (初日)。日付が無いライブでは `None`。
 */
dateBadge: DateBadge | null, 
/**
 * 期間の終端 (`〜 9/13 (日)`)。**1 日で終わるライブでは `None`**
 * (初日と同じ日を 2 度出さない。判断は `date_display::range_end`)。
 */
endDisplay: string | null, 
/**
 * 行に出すブランドの札。**ブランド別一覧では `None`** (全行同じ札を並べても
 * 見分けに効かない)。
 */
brandMark: Ref | null, 
/**
 * 会場をまとめた 1 行 (多いときは畳む)。
 */
venueDisplay: string | null, 
/**
 * 公演数 (`2 公演`)。**1 公演なら `None`** (数えるまでもないものに数を付けない)。
 */
showCountDisplay: string | null, 
/**
 * 種別 (`live` / `festival` / …)。
 */
kind: string, 
/**
 * 行に出す種別チップ。**既定の種別 (ライブ) には付かない** — ほぼ全行に同じ札が並んでも
 * 見分けにならず、フェス・リリースイベントのような例外だけを言えばよい。
 * 判断は `content::kind_chip` 1 箇所。
 */
kindLabel: string | null, };
