// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * どの切り口の一覧か。
 */
export type EventListKind = "index" | "upcoming" | "past" | "pastYear" | "brand";
