// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ref } from "./Ref";

/**
 * 出演者 1 人と、その公演での役割。
 */
export type EventCastMember = { ref: Ref, isLead: boolean, isGuest: boolean, };
