// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventCastMember } from "./EventCastMember";
import type { Ref } from "./Ref";

/**
 * 公演 1 本ぶんの出演者。
 */
export type EventCastShow = { show: Ref, performers: Array<EventCastMember>, };
