// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ref } from "./Ref";
import type { ShowIdolIds } from "./ShowIdolIds";

/**
 * 出演者マトリクス。
 */
export type EventCast = { 
/**
 * このライブのブランドに属するアイドル (表の行)。
 */
brandIdols: Array<Ref>, presenceByShow: Array<ShowIdolIds>, leadByShow: Array<ShowIdolIds>, guestByShow: Array<ShowIdolIds>, };
