// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ref } from "./Ref";

/**
 * ライブ一覧の 1 行。
 */
export type EventListItem = { ref: Ref, firstDate: string | null, lastDate: string | null, shortDate: string | null, brand: Ref | null, 
/**
 * 種別チップ (`live` / `festival` / …)。一覧を全種別で出すので、行で見分けが要る。
 */
kind: string, kindLabel: string, showCount: number, venueLabels: Array<string>, };
