// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventCastShow } from "./EventCastShow";

/**
 * 出演者。**公演ごとに、出た人と役割を結合済みで持つ。**
 *
 * 以前は「アイドル id の並行配列 3 本」(`presence` / `lead` / `guest`) だった。
 * 描画側が毎ページ id → 実体の結合と主演/ゲスト判定をやり直すことになり、
 * 「そのまま描ける形まで作り込む」という DTO の方針から外れていた。
 */
export type EventCast = { 
/**
 * 公演の並びは `shows_by_event` (date ASC, sort_order ASC) のまま。
 */
shows: Array<EventCastShow>, };
