// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppOpen } from "./AppOpen";
import type { EventCast } from "./EventCast";
import type { EventStats } from "./EventStats";
import type { Ref } from "./Ref";
import type { ReleaseInfo } from "./ReleaseInfo";
import type { SeoBlock } from "./SeoBlock";
import type { ShowSummary } from "./ShowSummary";
import type { TicketInfo } from "./TicketInfo";

/**
 * `/events/<id>/` の中身 (`events/<key>.json`)。
 */
export type EventPage = { schemaVersion: number, id: string, path: string, name: string, nameKana: string | null, themeKey: string, brand: Ref | null, 
/**
 * 合同ライブの相手ブランド (`events.joint_brand_ids` を分割して引いたもの)。
 */
jointBrands: Array<Ref>, 
/**
 * `live` / `festival` / `release_event` / `other` / `radio` / `stream`。
 */
kind: string, 
/**
 * 種別チップに出す日本語表記。
 */
kindLabel: string, eventType: string, firstDate: string | null, lastDate: string | null, 
/**
 * `first_date >= todayJst`。判定は `event_grouping::group_events_by_year` を
 * 1 要素で呼んだ結果で、**`>=` をここに書かない** (規則を二重に持たないため)。
 */
isUpcoming: boolean, ticket: TicketInfo, stats: EventStats, shows: Array<ShowSummary>, 
/**
 * `event_attendance` が `None` を返しうるので `Option`。
 * v1 の Web は公演ごとの出演者だけを出し、欠席マトリクスは描かない。
 */
cast: EventCast | null, 
/**
 * 円盤。Bundle DB では常に空。
 */
releases: Array<ReleaseInfo>, 
/**
 * 公演会場の重複排除 (初出順)。
 */
venues: Array<Ref>, app: AppOpen, seo: SeoBlock, };
