// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 選択肢 1 件。`value` は絞り込みの条件 (`SongQuery` / `IdolQuery`) にそのまま渡す文字列。
 */
export type FacetOption = { value: string, label: string, };
