// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NavLink } from "./NavLink";

/**
 * 一覧の頭の切替 1 軸 (ブランド・年・誕生月・都道府県・月…)。
 *
 * `label` は軸の名で、畳んだメニューの札に「軸 いまの値」と出る語。値は `links`
 * (現在地は `NavLink.current`)。どの軸をどの名で、どの順に出すかは Rust が決め、
 * Astro は並べるだけ。
 */
export type FilterAxis = { label: string, links: Array<NavLink>, };
