// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FoldCase } from "./FoldCase";

/**
 * 畳み込みのパリティ用フィクスチャ (`parity/fold.json`)。
 *
 * wasm 版 (Plan W) でも TS 移植版 (Plan F) でも、これを全件通すのが検収になる。
 */
export type FoldParity = { schemaVersion: number, cases: Array<FoldCase>, };
