// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ref } from "./Ref";

/**
 * 予測の 1 曲。
 */
export type ForecastRow = { rank: number, song: Ref, 
/**
 * セトリに入る推定確率 (0〜100 の整数)。
 */
percent: number, 
/**
 * 理由 (「オリメン全員出演」など)。表示の優先順。
 */
reasons: Array<string>, };
