// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ホール (同一会場内の区画)。
 */
export type HallRow = { name: string, capacity: number | null, 
/**
 * 収容人数の表記 (`9000人`)。人数が無ければ `None`。
 */
capacityDisplay: string | null, };
