// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppLinks } from "./AppLinks";
import type { BrandListItem } from "./BrandListItem";
import type { Countdown } from "./Countdown";
import type { EmptyText } from "./EmptyText";
import type { EventListItem } from "./EventListItem";
import type { NavLink } from "./NavLink";
import type { SeoBlock } from "./SeoBlock";
import type { ShowSummary } from "./ShowSummary";
import type { StatTile } from "./StatTile";

/**
 * トップページ (`/`)。
 */
export type HomePage = { schemaVersion: number, path: string, 
/**
 * ヒーローの大見出し (改行位置を含む行の列)。
 */
headline: Array<string>, 
/**
 * ヒーローの 1 行説明。
 */
tagline: string, 
/**
 * 見出しの上の日付欄 (`2026.09.24 THU`)。
 */
todayDisplay: string, 
/**
 * 次のライブ (今後のライブの先頭) までの残り日数の札。先頭の日付が読めなければ `None`。
 */
nextCountdown: Countdown | null, 
/**
 * 今後のライブ (直近 8 件)。
 */
upcoming: Array<EventListItem>, 
/**
 * 今後のライブが 1 件も無いときの案内。
 */
upcomingEmpty: EmptyText | null, 
/**
 * 最近の公演 (直近 8 件)。
 */
recentShows: Array<ShowSummary>, 
/**
 * 最近の公演が 1 件も無いときの案内。
 */
recentShowsEmpty: EmptyText | null, 
/**
 * 件数タイル (ライブ / 公演 / 楽曲 / アイドル / ユニット / 会場)。各一覧への入口を持つ。
 */
statTiles: Array<StatTile>, brands: Array<BrandListItem>, app: AppLinks, 
/**
 * 「アプリで、もっと」の説明文。アプリにしか無い機能の並びは `content` が 1 箇所で持つ
 * (歌詞を出面で出す/出さないで変わる)。
 */
appNote: string, 
/**
 * 「最近の公演」の続き先。公演だけの一覧は無いので、開催済みのライブへ送る。
 */
recentShowsMore: NavLink, seo: SeoBlock, };
