// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppLinks } from "./AppLinks";
import type { BrandListItem } from "./BrandListItem";
import type { EventListItem } from "./EventListItem";
import type { NavLink } from "./NavLink";
import type { SeoBlock } from "./SeoBlock";
import type { ShowSummary } from "./ShowSummary";
import type { StatTile } from "./StatTile";

/**
 * トップページ (`/`)。
 */
export type HomePage = { schemaVersion: number, path: string, 
/**
 * ヒーローの 1 行説明。
 */
tagline: string, 
/**
 * 「非公式ファンメイド」の断り書き。
 */
disclaimer: string, 
/**
 * 今後のライブ (直近 8 件)。
 */
upcoming: Array<EventListItem>, 
/**
 * 最近の公演 (直近 8 件)。
 */
recentShows: Array<ShowSummary>, 
/**
 * 件数タイル (ライブ / 公演 / 楽曲 / アイドル / ユニット / 会場)。各一覧への入口を持つ。
 */
statTiles: Array<StatTile>, brands: Array<BrandListItem>, app: AppLinks, 
/**
 * 「今後のライブ」「開催済み」等への入口。
 */
sectionLinks: Array<NavLink>, seo: SeoBlock, };
