// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppOpen } from "./AppOpen";
import type { EmptyText } from "./EmptyText";
import type { IdolPerformedRow } from "./IdolPerformedRow";
import type { IdolShowRow } from "./IdolShowRow";
import type { IdolSongSection } from "./IdolSongSection";
import type { ProfileRow } from "./ProfileRow";
import type { Ref } from "./Ref";
import type { SeoBlock } from "./SeoBlock";
import type { StatTile } from "./StatTile";
import type { TagChipDto } from "./TagChipDto";
import type { VoiceActorRow } from "./VoiceActorRow";

/**
 * `/idols/<id>/` の中身。
 */
export type IdolPage = { schemaVersion: number, id: string, path: string, name: string, nameKana: string | null, themeKey: string, 
/**
 * 主ブランド。
 * コミュニティが付けたタグ (多い順)。焼き込み。
 */
tags: Array<TagChipDto>, brand: Ref | null, 
/**
 * `idol_brands` (primary 先頭)。掛け持ちのアイドルが居る。
 */
brands: Array<Ref>, 
/**
 * `screen_composition::idol_profile_rows` の結果。
 * **並べる判断はコアが持つ**ので、web は行を上から出すだけ。
 */
profileRows: Array<ProfileRow>, currentVoiceActor: string | null, 
/**
 * CV の履歴。**交代があったときだけ入る** (1 人だけなら現任の行と同じことしか
 * 言わないので空)。出す/出さないの線は Rust が引く。
 */
voiceActorHistory: Array<VoiceActorRow>, units: Array<Ref>, 
/**
 * 持ち曲を ソロ曲 / ユニット曲 / 全体曲 / カバー / その他 の棚に分けたもの
 * (`idol_song_queries::idol_original_song_sections`。アプリの持ち歌と同じ棚)。
 * 棚の中は release_date 降順。曲の無い棚は来ない。
 */
songSections: Array<IdolSongSection>, 
/**
 * 持ち曲が 1 曲も無いときの案内。
 */
songsEmpty: EmptyText | null, 
/**
 * 歌ったことのある曲。
 */
performedSongs: Array<IdolPerformedRow>, shows: Array<IdolShowRow>, description: string | null, 
/**
 * 数の帯 (持ち曲 / ライブで歌った曲 / 出演公演)。ページ内の該当の節へ飛ぶ。
 */
statTiles: Array<StatTile>, app: AppOpen, seo: SeoBlock, };
