// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FacetOption } from "./FacetOption";
import type { SortOption } from "./SortOption";

/**
 * アイドル一覧の選択肢。
 */
export type IdolFacets = { 
/**
 * 一覧に実際に居るアイドルのブランドだけ。
 */
brands: Array<FacetOption>, 
/**
 * 属性は実データに出てくるものだけ (ブランドごとに語彙が違う)。
 */
attributes: Array<FacetOption>, 
/**
 * 誕生月 (1〜12)。値は `IdolQuery.birth_month` の数を文字列にしたもの。
 */
birthMonths: Array<FacetOption>, sorts: Array<SortOption>, 
/**
 * 既定の並べ替え (公式順)。
 */
defaultSort: string, };
