// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IdolSongRow } from "./IdolSongRow";

/**
 * 持ち曲の棚 1 つ。
 */
export type IdolSongSection = { 
/**
 * 見出し (`ソロ曲`)。
 */
heading: string, 
/**
 * 棚の切替に出す短い形 (`ソロ`)。
 */
shortHeading: string, 
/**
 * ページ内リンクの着地 (`idol-songs-solo`)。
 */
anchor: string, songs: Array<IdolSongRow>, };
