// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EmptyText } from "./EmptyText";
import type { FilterAxis } from "./FilterAxis";
import type { IdolColumn } from "./IdolColumn";
import type { IdolListItem } from "./IdolListItem";
import type { IdolListKind } from "./IdolListKind";
import type { IdolQuery } from "./IdolQuery";
import type { Ref } from "./Ref";
import type { SeoBlock } from "./SeoBlock";

/**
 * アイドル一覧ページ。`/idols/` `/idols/brand/<brandId>/` `/idols/birth-month/<m>/`。
 */
export type IdolListPage = { schemaVersion: number, path: string, title: string, kind: IdolListKind, brand: Ref | null, items: Array<IdolListItem>, 
/**
 * 表の見出し (名前の列の次から)。全行が空になる列は出さない。
 */
columns: Array<IdolColumn>, 
/**
 * 名前の列。他の列と同じ器にしてあるので、見出しの出し方を分岐させずに済む。
 */
nameColumn: IdolColumn, 
/**
 * 畳んだメニューにする軸 (ブランド・誕生月)。
 */
filters: Array<FilterAxis>, total: number, 
/**
 * 島の絞り込みの土台。ブラウザの wasm がこれに入力された軸を足して
 * `filter_idol_list` / `sort_idol_list` を回す。
 *
 * **ブランドと誕生月は入れない。** この一覧の行は `idol_queries::idol_list` /
 * `idols_by_birth_month` が組んでいて (2 つ目のブランドのアイドルも載る)、島の条件
 * (主ブランドだけで当たる) で絞り直すと行が消える。島が絞る母集団はページの行で、
 * 土台は「ページの行を必ず含む」条件であればよい。
 */
queryBase: IdolQuery, 
/**
 * ページが値を決めている軸の鍵 (`brandIds` / `birthMonth`)。島はこの軸を出さない。
 */
fixedAxes: Array<string>, 
/**
 * 1 人も居ないときの案内。
 */
empty: EmptyText | null, seo: SeoBlock, };
