// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ref } from "./Ref";

/**
 * 「歌ったことのある曲」の 1 行 (原唱者でなくても披露していれば載る)。
 */
export type IdolPerformedRow = { song: Ref, times: number, 
/**
 * 行の副題 (ユニット名・披露回数)。空なら `None`。
 */
subtitle: string | null, };
