// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ref } from "./Ref";

/**
 * アイドル一覧の 1 行。
 */
export type IdolListItem = { ref: Ref, brand: Ref | null, currentVoiceActor: string | null, birthdayDisplay: string | null, };
