// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IdolListItem } from "./IdolListItem";
import type { IdolListKind } from "./IdolListKind";
import type { NavLink } from "./NavLink";
import type { Ref } from "./Ref";
import type { SeoBlock } from "./SeoBlock";

/**
 * アイドル一覧ページ。`/idols/` `/idols/brand/<brandId>/` `/idols/birth-month/<m>/`。
 */
export type IdolListPage = { schemaVersion: number, path: string, title: string, kind: IdolListKind, brand: Ref | null, 
/**
 * 誕生月別のときだけ入る (1–12)。
 */
birthMonth: number | null, items: Array<IdolListItem>, brandLinks: Array<NavLink>, birthMonthLinks: Array<NavLink>, total: number, seo: SeoBlock, };
