// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppOpen } from "./AppOpen";
import type { IdolPerformedRow } from "./IdolPerformedRow";
import type { IdolShowRow } from "./IdolShowRow";
import type { IdolSongRow } from "./IdolSongRow";
import type { ProfileRow } from "./ProfileRow";
import type { Ref } from "./Ref";
import type { SeoBlock } from "./SeoBlock";
import type { VoiceActorRow } from "./VoiceActorRow";

/**
 * `/idols/<id>/` の中身。
 */
export type IdolPage = { schemaVersion: number, id: string, path: string, name: string, nameKana: string | null, themeKey: string, 
/**
 * 表示名の先頭 1 文字 (アプリの `ImasAvatar` と同じ)。画像は載せない。
 */
monogram: string, 
/**
 * 主ブランド。
 */
brand: Ref | null, 
/**
 * `idol_brands` (primary 先頭)。掛け持ちのアイドルが居る。
 */
brands: Array<Ref>, color: string | null, 
/**
 * `screen_composition::idol_profile_rows` の結果。
 * **並べる判断はコアが持つ**ので、web は行を上から出すだけ。
 */
profileRows: Array<ProfileRow>, currentVoiceActor: string | null, voiceActorHistory: Array<VoiceActorRow>, units: Array<Ref>, 
/**
 * 持ち曲 (release_date 降順)。
 */
songs: Array<IdolSongRow>, 
/**
 * 歌ったことのある曲。
 */
performedSongs: Array<IdolPerformedRow>, shows: Array<IdolShowRow>, description: string | null, app: AppOpen, seo: SeoBlock, };
