// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 一覧の絞り込み条件を、**出面 (JSON) で運ぶための形**。
 *
 * `IdolListFilterCriteria` のうち、ログインもユーザーデータも持たない出面で
 * 意味のある軸だけ + 並べ替え。`SongQuery` と同じ流儀で、
 * **Rust ↔ wasm ↔ TS の唯一の定義**にする。
 */
export type IdolQuery = { 
/**
 * 空 = 全ブランド。
 */
brandIds: Array<string>, 
/**
 * ブランド内サブ属性 (cute/cool/passion 等)。
 */
attribute: string | null, 
/**
 * 誕生月 (1..=12)。
 */
birthMonth: number | null, 
/**
 * 名前 / かな / CV 名 / 別名 / 愛称の部分一致。
 */
searchText: string, 
/**
 * `IdolSortKind::key()` の値。未知の鍵は既定 (公式順) に倒れる。
 */
sort: string, 
/**
 * 省略時はその並びの既定方向。
 */
ascending: boolean | null, };
