// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppOpen } from "./AppOpen";
import type { IdolPerformedRow } from "./IdolPerformedRow";
import type { IdolShowRow } from "./IdolShowRow";
import type { IdolSongRow } from "./IdolSongRow";
import type { ProfileRow } from "./ProfileRow";
import type { Ref } from "./Ref";
import type { SeoBlock } from "./SeoBlock";
import type { StatTile } from "./StatTile";
import type { TagChipDto } from "./TagChipDto";
import type { VoiceActorRow } from "./VoiceActorRow";

/**
 * `/idols/<id>/` の中身。
 */
export type IdolPage = { schemaVersion: number, id: string, path: string, name: string, nameKana: string | null, 
/**
 * ヒーローの絵の代わりに置く短い名 (`Ref.monogram` と同じ規則)。
 */
monogram: string, themeKey: string, 
/**
 * 主ブランド。
 * コミュニティが付けたタグ (多い順)。焼き込み。
 */
tags: Array<TagChipDto>, brand: Ref | null, 
/**
 * `idol_brands` (primary 先頭)。掛け持ちのアイドルが居る。
 */
brands: Array<Ref>, color: string | null, 
/**
 * `screen_composition::idol_profile_rows` の結果。
 * **並べる判断はコアが持つ**ので、web は行を上から出すだけ。
 */
profileRows: Array<ProfileRow>, currentVoiceActor: string | null, voiceActorHistory: Array<VoiceActorRow>, units: Array<Ref>, 
/**
 * 持ち曲 (release_date 降順)。
 */
songs: Array<IdolSongRow>, 
/**
 * 歌ったことのある曲。
 */
performedSongs: Array<IdolPerformedRow>, shows: Array<IdolShowRow>, description: string | null, 
/**
 * 数の帯 (持ち曲 / ライブで歌った曲 / 出演公演)。ページ内の該当の節へ飛ぶ。
 */
statTiles: Array<StatTile>, app: AppOpen, seo: SeoBlock, };
