// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ref } from "./Ref";

/**
 * 持ち曲の 1 行。
 */
export type IdolSongRow = { song: Ref, 
/**
 * `song_artists.role` (`original` / `cover` 等)。
 */
role: string | null, releaseDate: string | null, performanceCount: number, };
