// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IdolListItem } from "./IdolListItem";
import type { IdolListKind } from "./IdolListKind";
import type { IdolQuery } from "./IdolQuery";
import type { NavLink } from "./NavLink";
import type { Ref } from "./Ref";
import type { SeoBlock } from "./SeoBlock";

/**
 * アイドル一覧ページ。`/idols/` `/idols/brand/<brandId>/` `/idols/birth-month/<m>/`。
 */
export type IdolListPage = { schemaVersion: number, path: string, title: string, kind: IdolListKind, brand: Ref | null, 
/**
 * 誕生月別のときだけ入る (1–12)。
 */
birthMonth: number | null, items: Array<IdolListItem>, brandLinks: Array<NavLink>, birthMonthLinks: Array<NavLink>, total: number, 
/**
 * この一覧を組んだときの条件。ブラウザの wasm がこれを土台に
 * 条件を足して `filter_idol_list` / `sort_idol_list` を回す
 * (曲一覧の `SongListPage.query_base` と同じ仕掛け)。
 */
queryBase: IdolQuery, seo: SeoBlock, };
