// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * アイドル一覧の表の列 1 つ (名前の列の次から)。
 */
export type IdolColumn = { label: string, 
/**
 * 数の列 (右に寄せ、等幅で出す)。
 */
numeric: boolean, 
/**
 * この列で並べ替えられるときの鍵 (`IdolSortKind::key`)。
 * `None` の列は押しても何も起きないので、見出しをボタンにしない。
 */
sortKey: string | null, };
