// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ref } from "./Ref";

/**
 * 出演公演の 1 行。
 */
export type IdolShowRow = { show: Ref, event: Ref, date: string, shortDate: string, venueLabel: string | null, 
/**
 * このアイドルがこの公演で歌った曲数。
 */
songCount: number, };
