// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * かな目次の 1 区画。
 */
export type KanaSection = { 
/**
 * 「あ」「か」…「英数」「その他」。
 */
label: string, 
/**
 * `items` の何番目から始まるか。
 */
startIndex: number, count: number, };
