// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Lineup } from "./Lineup";
import type { MissingOriginals } from "./MissingOriginals";

/**
 * 歌唱者と原唱者 (オリメン) の関係の札。
 */
export type LineupNote = { 
/**
 * 関係の種類 (`original` / `originalPlus` / `partial` / `cover`)。CSS の見分け用。
 */
kind: Lineup, 
/**
 * `オリメン` / `オリメン+α` / `オリメン 4/5` (何人中何人いるか) / `オリメン不在`。
 */
label: string, 
/**
 * 歌っていない原唱者のうち、**その公演には出ている人**。いなければ `None`。
 * 公演にいない人は出演者一覧で分かるので並べず、数は `label` が持つ
 * (規則は `domain::setlist_lineup::absent_in_cast`)。
 */
missing: MissingOriginals | null, };
