// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ref } from "./Ref";

/**
 * 途中にリンクを 1 つ挟んだ 1 文 (`この曲は <派生元> の派生曲です。`)。
 * 文の前後は Rust が持ち、受け手はリンクを挟んで並べるだけ。
 */
export type LinkedNote = { before: string, link: Ref, after: string, };
