// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CallGuideVocabulary } from "./CallGuideVocabulary";

/**
 * 歌詞とコールガイドの出し方。
 *
 * **本文はここに入らない。** 歌詞は D1 にしかなく、1 リクエスト 1 曲で
 * 取りに行く形でしか配れない (まとめて取れないことが許諾の条件)。
 * ここが持つのは「出すか」「どこへ取りに行くか」「何を掲示するか」だけ。
 */
export type LyricsBlock = { 
/**
 * この出面で歌詞を出すか。false ならボタンも取得先も出ない。
 */
available: boolean, 
/**
 * 出さないときの状態の札 (`JASRAC 許諾待ち`)。出しているときは `None`。
 */
statusLabel: string | null, 
/**
 * 出さないときの案内文 (アプリへ誘導する)。
 */
note: string, 
/**
 * 出すときに必ず掲示する許諾番号。
 */
licenseNumber: string | null, 
/**
 * 出すときに添える説明 (許諾番号つき)。
 */
licenseNote: string | null, 
/**
 * 歌詞 1 曲の取得先 (絶対 URL)。**1 曲ぶんだけ返る。**
 */
sourceUrl: string | null, 
/**
 * 取りに行くボタンの文言 (`歌詞とコールガイドを読む`)。出さないときは `None`。
 */
readLabel: string | null, 
/**
 * コールガイドの語彙 (記号・札・凡例の語)。出すときだけ。
 */
callGuide: CallGuideVocabulary | null, };
