// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ref } from "./Ref";

/**
 * 「いたのに歌わなかった」原唱者の並び。言葉 (`不参加`) と人を一緒に運ぶ。
 */
export type MissingOriginals = { label: string, 
/**
 * 原唱者の並び順。空にはならない。
 */
idols: Array<Ref>, };
