// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 年の束の中の 1 か月ぶん (`events` の先頭から `count` 件ずつ)。
 */
export type MonthSpan = { 
/**
 * 柱に大きく置く数 (`"9"`)。月が読めない区間では空。
 */
number: string, 
/**
 * 数に添える字 (`"月"`)。月が読めない区間では `"日程未定"`。
 */
unit: string, count: number, };
