// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 一覧ページ間の切替リンク (ブランド別など)。
 *
 * クライアント状態を持たせないため、切替は必ず「別ページへのリンク」になる。
 */
export type NavLink = { label: string, path: string, 
/**
 * いま見ているページか (`aria-current="page"` を付ける材料)。
 */
current: boolean, 
/**
 * ブランド切替のときだけ入る。行にブランド色を当てるのに使う。
 */
themeKey: string | null, 
/**
 * 件数を出せるときだけ入る。
 */
count: number | null, };
