// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SeoBlock } from "./SeoBlock";
import type { SiteEntry } from "./SiteEntry";

/**
 * 見つからないページ (`404.html`)。`SiteMeta::not_found` に入る。
 *
 * ルート台帳に載らない (sitemap にもリンクにも出ない) ので、ページ単位の JSON を
 * 持たせずメタに同居させる。
 */
export type NotFoundPage = { 
/**
 * ヒーローの上の小さな札 (`404`)。
 */
eyebrow: string, title: string, lede: string, 
/**
 * 「ここから探す」入口 (ライブ / 楽曲 / アイドル)。
 */
entries: Array<SiteEntry>, seo: SeoBlock, };
