// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ペンライトの色セット 1 件。
 */
export type PenlightSetDto = { 
/**
 * 色セットの鍵 (アプリ側が色に解決する)。
 */
key: string, count: number, };
