// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ref } from "./Ref";

/**
 * 歌唱メンバー 1 人。
 */
export type PerformerRef = { ref: Ref, 
/**
 * 表示名 (CV 名で歌った回など、アイドル名と違うことがある)。
 * 表示名 (CV 名で歌った回など、アイドル名と違うことがある)。
 * アイドル名そのものは `reference.name` にある。
 */
displayName: string, };
