// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateBadge } from "./DateBadge";
import type { Ref } from "./Ref";

/**
 * 披露履歴の 1 行。
 */
export type PerformanceRow = { show: Ref, event: Ref, date: string, 
/**
 * 行の左端に置く日付ブロック。
 */
dateBadge: DateBadge, venue: string | null, 
/**
 * その公演で何曲目に披露されたか (1 始まり)。0 は不明。
 */
number: number, 
/**
 * 1 行で出すときの場所表記 (公演名と会場を `" ・ "` で繋いだもの)。
 */
placeDisplay: string, 
/**
 * 行の飛び先。公演ページのその曲の行 (`…/#setlist-N`)。曲順が分からなければ公演ページの頭。
 */
href: string, 
/**
 * この披露の歌唱メンバー (3 人まで並べて残りは「ほか N 人」)。無ければ None。
 */
performersDisplay: string | null, 
/**
 * 「初披露」または「N 回目」(この DB に載っている範囲で、最古から数えて)。
 */
ordinalLabel: string, };
