// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ref } from "./Ref";

/**
 * 歌唱メンバー 1 人。
 */
export type PerformerRef = { ref: Ref, 
/**
 * 現任 CV 名。**アイドル名と違うときだけ入る** (CV 不在なら `None`)。
 * アイドル名は `reference.name`。
 *
 * **どちらを出すかは受け手が決めない。** 表示の規則は
 * `domain::event_detail_queries::performer_display_name` が持ち、
 * 閲覧者が選んだモードに従って主/副を返す。ここは素材を両方渡すだけで、
 * 「同じ名前を 2 つ持たせない」判断もその関数 (`Both` の副) に任せる。
 */
castName: string | null, };
