// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CastKind } from "./CastKind";
import type { Ref } from "./Ref";

/**
 * 歌唱メンバー 1 人。
 */
export type PerformerRef = { ref: Ref, 
/**
 * その公演でアイドルを演じた人の名前 (公演日の CV。舞台なら俳優)。
 * **アイドル名と違うときだけ入る** (演者不明なら `None`)。
 * アイドル名は `reference.name`。決め方は `event_detail_queries::show_performer`。
 *
 * **どちらを出すかは受け手が決めない。** 表示の規則は
 * `domain::event_detail_queries::performer_display_name` が持ち、
 * 閲覧者が選んだモードに従って主/副を返す。ここは素材を両方渡すだけで、
 * 「同じ名前を 2 つ持たせない」判断もその関数 (`Both` の副) に任せる。
 */
castName: string | null, 
/**
 * `cast_name` が声優か俳優か。俳優 (`stage`) には「CV.」を添えない。
 */
castKind: CastKind, };
