// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ref } from "./Ref";

/**
 * 披露履歴の 1 行。
 */
export type PerformanceRow = { show: Ref, event: Ref, date: string, shortDate: string, venue: string | null, position: number, section: string | null, };
