// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 歌唱者の表示モード 1 つぶん。
 */
export type PerformerNameOptionDto = { 
/**
 * localStorage に残す値。iOS/Android の保存値と同じ文字列。
 */
raw: string, label: string, };
