// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PollSummaryDto } from "./PollSummaryDto";
import type { SeoBlock } from "./SeoBlock";

/**
 * お題の一覧 (`/polls/`)。
 *
 * **読むだけ。** 投票はログインが要るのでアプリへ誘導する。
 * 中身は D1 の集計を焼き込んだもので、閲覧時に D1 は読まない。
 */
export type PollListPage = { schemaVersion: number, path: string, title: string, polls: Array<PollSummaryDto>, total: number, seo: SeoBlock, };
