// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PollEntryDto } from "./PollEntryDto";

/**
 * お題 1 件と、その時点の得票。
 */
export type PollSummaryDto = { id: string, title: string, description: string | null, 
/**
 * 何を選ぶお題か (「曲」「アイドル」)。語は Rust が決める。
 */
targetLabel: string, 
/**
 * 締切 (`YYYY-MM-DD`)。無期限なら None。
 */
endsOn: string | null, 
/**
 * 締切の日付に添える語 (締切前は「締切」、過ぎたら「終了」)。無期限なら `None`。
 */
endsLabel: string | null, totalVotes: number, 
/**
 * 上位の得票。同数は entity id 順で安定させる。
 */
entries: Array<PollEntryDto>, };
