// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ref } from "./Ref";

/**
 * お題の得票 1 行。
 */
export type PollEntryDto = { ref: Ref, votes: number, 
/**
 * 1 始まりの順位 (同数でも別の順位を振る = 表示の通し番号)。
 */
rank: number, };
