// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * プロフィールの 1 行。
 */
export type ProfileRow = { label: string, value: string, 
/**
 * `"plain"` | `"monospaced"` | `"colorSwatch"` (`screen_composition::RowStyle` の写し)。
 */
style: string, 
/**
 * 誕生日の行だけ `/idols/birth-month/<m>/` が入る。
 * `CopyValue` / `ToggleExpansion` は Web に書き込み・状態が無いので `None` に落とす。
 */
link: string | null, };
