// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilterAxis } from "./FilterAxis";
import type { RankRow } from "./RankRow";
import type { SeoBlock } from "./SeoBlock";
import type { YearBar } from "./YearBar";

/**
 * ランキング (`/ranking/` と `/ranking/brand/<brandId>/`)。
 *
 * アプリの「調べる」のうち、個人の記録に依らない集計だけ。数え方は
 * `domain::stats_queries` (アプリと同じ関数) で、Web 側で数え直さない。
 */
export type RankingPage = { schemaVersion: number, path: string, title: string, lede: string, 
/**
 * すべて / ブランドごと の切替。
 */
scope: FilterAxis, 
/**
 * よく披露される曲。
 */
songs: Array<RankRow>, 
/**
 * 出演公演が多いアイドル。
 */
idols: Array<RankRow>, 
/**
 * ブランド別の楽曲数。ブランドのページでは空 (1 本だけの棒は何も言わない)。
 */
brandSongs: Array<RankRow>, 
/**
 * 年ごとの公演数 (古い年から)。
 */
years: Array<YearBar>, 
/**
 * 年の棒に添える注記 (今年以降は予定を含む)。
 */
yearsNote: string | null, seo: SeoBlock, };
