// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ref } from "./Ref";

/**
 * ランキングの 1 行。棒の長さは 1 位 (ブランド別は最大値) に対する千分率。
 */
export type RankRow = { 
/**
 * 1 始まりの通し番号。順位を振らない表 (ブランド別) では None。
 */
rank: number | null, ref: Ref, value: number, 
/**
 * 数の単位 (「回」「公演」「曲」)。
 */
unit: string, sharePermille: number, };
