// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RefKind } from "./RefKind";

/**
 * 他ページへのリンク 1 個。
 *
 * **web はこれ以上の情報から href を組み立てない。** [`Self::path`] をそのまま
 * `href` に入れる。エンコードのコードを TS に書かせないための型。
 */
export type Ref = { kind: RefKind, 
/**
 * 生の id (アプリ連携・deeplink 用)。**href の材料にしない。**
 */
id: string, name: string, 
/**
 * 補助表記 (公演なら日付、曲ならユニット名 等)。
 */
sub: string | null, 
/**
 * 絵の代わりに丸に置く短い名 (アイドルだけ。規則は `emit::glyph::idol_monogram`)。
 * 版権物ゼロなので顔写真は無く、アプリの ImasAvatar と同じモノグラムで「顔」を作る。
 * `artwork_url` と同じく、種別で埋まる `Ref` の任意項目。
 */
monogram: string | null, 
/**
 * 先頭・末尾スラッシュ付きの完成形 URL (percent-encode 済み)。
 */
path: string, 
/**
 * `themes.css` のセレクタキー (`idol:<id>` / `brand:<id>` / `neutral`)。
 * HTML は `data-theme` 属性にこれを 1 個置くだけでよい。
 */
themeKey: string, 
/**
 * ジャケ画像 (Apple Music CDN)。曲以外は常に `None`。
 * **これがサイト唯一の外部画像**で、版権物はこれ以外に載せない。
 */
artworkUrl: string | null, };
