// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * [`Ref`] が指す先の種別。
 */
export type RefKind = "event" | "show" | "song" | "idol" | "unit" | "venue" | "brand";
