// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 円盤 (Blu-ray / DVD / CD)。
 */
export type ReleaseInfo = { id: string, title: string, kind: string | null, releaseDate: string | null, url: string | null, };
