// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 検索エンジンへの指示。
 *
 * `other` ブランド (ラブライブ等、他フランチャイズの合同ライブ楽曲) 配下は
 * [`Self::NoindexFollow`] にする。非公式ファンサイトが他フランチャイズ名で
 * 検索流入を取りにいかないための判断で、**判断は Rust 側で済ませ**、Astro は
 * `<meta name="robots">` と sitemap の filter に写すだけにする。
 */
export type Robots = "index,follow" | "noindex,follow";
