// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RouteEntry } from "./RouteEntry";

/**
 * 全ルートの台帳 (`routes.json`)。sitemap の生成と、到達性テストに使う。
 */
export type RoutesFile = { schemaVersion: number, routes: Array<RouteEntry>, 
/**
 * `robots` が `noindex,*` のページの完成形 path。
 *
 * [`RouteEntry::in_sitemap`] と同じ判断の裏返しだが、こちらは
 * `astro.config.mjs` の `@astrojs/sitemap` の `filter(url)` から
 * **ページ JSON を 1 本も開かずに**引けるように、平たい配列で持たせてある。
 * 判断そのものは Rust 側 ([`super::common::Robots`]) にあり、Astro は写すだけ。
 */
noindexPaths: Array<string>, };
