// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RouteKind } from "./RouteKind";

/**
 * ルート 1 本。
 *
 * ## Astro 側での使い分け (ここを取り違えると 404 になる)
 *
 * | フィールド | 使い道 |
 * |---|---|
 * | [`Self::path`] | `href` にそのまま入れる完成形 URL (percent-encode 済み・末尾スラッシュ付き) |
 * | [`Self::key`] | `getStaticPaths` の `params` に渡す値 (**Astro が encode する前**の生の値) |
 * | [`Self::id`] | DB 上の id (詳細ページのみ)。アプリ連携・deeplink 用。**URL の材料にしない** |
 *
 * `key` と `id` は通常は同じ文字列だが、危険な文字を含む id では `key` だけが
 * フォールバック slug に落ちる。`params` に `id` を渡すと、その 2 件だけ
 * 出力されないページを指すことになる。
 */
export type RouteEntry = { 
/**
 * 末尾スラッシュ付きの完成形 URL。
 */
path: string, kind: RouteKind, 
/**
 * `getStaticPaths` の params に渡す値。
 *
 * 詳細ページでは安全化済みのセグメント (= `url::path_key` の出力)、
 * パラメータを取る一覧ページでは param の生値 (年 `"2016"` / ブランド id `"ml"` /
 * 月 `"4"` / 都道府県 `"東京都"`)。params を取らないルートは `None`。
 */
key: string | null, 
/**
 * DB 上の id (詳細ページのみ)。アプリ連携・deeplink 用で、**URL の材料にしない**。
 * 一覧ページでは `None`。
 */
id: string | null, 
/**
 * このページを描くのに読む JSON の、`web/data/` からの相対パス。
 */
data: string, 
/**
 * sitemap に載せるか (`noindex` は載せない)。
 */
inSitemap: boolean, };
