// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ルートの種別。
 *
 * **粒度は「Astro のルートファイル 1 本」に揃えてある。** `/events/past/[year]/` と
 * `/events/brand/[brandId]/` を同じ `eventList` にまとめてしまうと、`getStaticPaths` が
 * params の集合を取り出すのに `path` を文字列で刻むことになり、URL の組み立て規則が
 * TypeScript 側に生えてしまう。1 種別 = 1 ルートファイルにしておけば
 *
 * ```ts
 * routes().routes
 *   .filter(r => r.kind === "eventListPastYear")
 *   .map(r => ({ params: { year: r.key! }, props: { data: r.data } }))
 * ```
 *
 * で済み、TS 側には規則が 1 つも残らない。
 */
export type RouteKind = "home" | "about" | "search" | "eventListIndex" | "eventListUpcoming" | "eventListPast" | "eventListPastYear" | "eventListBrand" | "songListIndex" | "songListBrand" | "songListAll" | "idolListIndex" | "idolListBrand" | "idolListBirthMonth" | "unitListIndex" | "unitListBrand" | "venueListIndex" | "venueListPref" | "brandList" | "event" | "show" | "song" | "idol" | "unit" | "venue" | "brand";
