// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RefKind } from "./RefKind";
import type { SearchRow } from "./SearchRow";

/**
 * 検索索引の 1 シャード。
 *
 * **照合の式はブラウザ側の `row.f.includes(foldedQuery)` 1 行だけ。**
 * 前方一致優先やスコアリングを足さない。並びは各シャードの元の並び
 * (= コアが決めた順) をそのまま保つ。
 */
export type SearchShard = { schemaVersion: number, kind: RefKind, 
/**
 * 畳み済みフィールドの区切り (`"\u{0001}"`)。
 *
 * 連結して 1 本にするとフィールド境界をまたぐ偽陽性が出る
 * (`TextSearchIndex` がフィールドを連結しない理由と同じ)。検索語にこの文字は
 * 入らないので、区切りを挟んだ `includes` は `TextSearchIndex::matches` と等価になる。
 * **定数だが JSON に明示する** — ブラウザ側に規則をハードコードさせないため。
 */
sep: string, 
/**
 * 行の href を組む前置き (`"/songs/"`)。
 * href は `pathPrefix + encodeURIComponent(row.k) + "/"`。これは**配管であって規則ではない**
 * (規則側の判断 = 危険な id をどう安全化するかは `row.k` に織り込み済み)。
 */
pathPrefix: string, rows: Array<SearchRow>, };
