// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SearchShardMeta } from "./SearchShardMeta";

/**
 * シャードの一覧 (`search/manifest.json`)。
 * island はまずこれを読み、4 本を並列取得する。
 */
export type SearchManifest = { schemaVersion: number, shards: Array<SearchShardMeta>, };
