// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RefKind } from "./RefKind";

/**
 * シャード 1 本のメタ。
 */
export type SearchShardMeta = { kind: RefKind, 
/**
 * `/search/songs.json` 等 (サイトルートからの絶対パス)。
 */
path: string, 
/**
 * セクション見出しに出す日本語 (「楽曲」「アイドル」…)。
 */
label: string, count: number, bytes: number, };
