// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 索引の 1 行。キーを 1 文字にしてあるのは、4 シャード合計で 1MB 級になるため。
 */
export type SearchRow = { 
/**
 * 表示名。
 */
n: string, 
/**
 * 補助表記 (曲=ユニット名 / ライブ=年 / 会場=都道府県 / アイドル=ブランド名)。
 */
s: string | null, 
/**
 * URL セグメントの素材。
 *
 * **生の id とは限らない**: 危険な文字を含む id はフォールバック slug に落ちており、
 * ここにはその結果 (= `url::path_key` の出力) が入る。生 id を使うと該当ページが
 * 404 になるので、href はこの値だけから組むこと。
 */
k: string, 
/**
 * 畳み済みフィールドを `sep` で連結したもの。
 */
f: string, };
