// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SeoBlock } from "./SeoBlock";

/**
 * 検索ページ (`/search/`, `index/search.json`) の文面。
 *
 * 検索の中身 (索引) は `search/*.json` で、ここはページの見出し・説明・`<head>` だけ。
 * 歌詞検索を出すかどうかで言うことが変わるので、文面も Rust が持つ
 * (`content::LYRICS_ON_WEB` を見る)。
 */
export type SearchPage = { schemaVersion: number, path: string, title: string, 
/**
 * 見出しの下の説明。
 */
lede: string, 
/**
 * 種別ごとに並べる件数の上限 (`domain::search_limits::WEB_SEARCH_LIMIT_PER_KIND`)。
 */
limitPerKind: number, 
/**
 * 歌詞を探す最小文字数 (`domain::search_limits::WEB_LYRICS_SEARCH_MIN_CHARS`)。
 */
lyricsMinChars: number, seo: SeoBlock, };
