// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RefKind } from "./RefKind";

/**
 * シャード 1 本のメタ。
 */
export type SearchShardMeta = { kind: RefKind, 
/**
 * 取得先 (`/search/songs.json`)。
 *
 * フィールド名が `path` でないのは、**JSON 中の `path` は必ずページの URL**、
 * という不変条件を全体で保つため (到達性テストが `path` を機械的に辿れる)。
 * これはページではなくデータファイルの場所なので `url` にしてある。
 */
url: string, 
/**
 * セクション見出しに出す日本語 (「楽曲」「アイドル」…)。
 */
label: string, count: number, bytes: number, };
