// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Crumb } from "./Crumb";
import type { Robots } from "./Robots";

/**
 * `<head>` に入れるものと、パンくず。
 */
export type SeoBlock = { title: string, description: string, 
/**
 * 絶対 URL。
 */
canonical: string, 
/**
 * OGP 画像の絶対 URL。
 */
ogImage: string, robots: Robots, 
/**
 * `<script type="application/ld+json">` にそのまま流し込む値。
 * 構造の判断 (どの型を出すか) は Rust 側で済ませてある。
 *
 * TS 型を手で指定しているのは、ts-rs の `serde-json-impl` に任せると
 * `JsonValue` が `<CARGO_MANIFEST_DIR>/bindings/` に落ち、生成された `.ts` が
 * `web/` の外を `import` しに行くため (Astro の tsconfig の外に出る)。
 * JSON-LD の最上位は必ずオブジェクトなので、この 1 行で十分。
 */
jsonLd: Record<string, unknown>, breadcrumbs: Array<Crumb>, };
