// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PerformerRef } from "./PerformerRef";
import type { Ref } from "./Ref";

/**
 * セトリの 1 行。
 */
export type SetlistRow = { id: string, position: number, 
/**
 * アンコール等の区切り。
 */
section: string | null, notes: string | null, 
/**
 * `setlist_items.unit_name`。**この披露限りの表記**で、曲のユニットとは別物。
 */
unitLabel: string | null, song: Ref, 
/**
 * 歌唱メンバー。`display_name` は**コアが現任 CV で解決済み**。
 */
performers: Array<PerformerRef>, 
/**
 * 原唱者 (`song_artists.role = 'original'`)。
 */
originalArtists: Array<Ref>, 
/**
 * `songs.song_type == "cover"`。
 */
isCover: boolean, };
