// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SetlistNoteTone } from "./SetlistNoteTone";

/**
 * 軸の中の事実 1 つ。強調は `tone` で出し分ける (文字列を見て決めない)。
 */
export type SetlistNote = { text: string, tone: SetlistNoteTone, };
