// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `domain::screen_composition::RowNoteTone` の写し。
 */
export type SetlistNoteTone = "value" | "detail" | "debut" | "mine" | "missing";
