// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PerformerRef } from "./PerformerRef";
import type { Ref } from "./Ref";

/**
 * セトリの 1 行。
 */
export type SetlistRow = { id: string, 
/**
 * **公演内で何曲目か (1 始まり)。画面に出す番号はこちら。**
 *
 * [`Self::position`] は `setlist_items` 全体を通した並び順の値で、実データでは
 * 11593 のような大きな数になる。並べ替えの鍵としては正しいが、そのまま番号として
 * 描くと読めない。どちらを出すかは表示の判断なので、Rust 側で決めておく。
 */
number: number, 
/**
 * 並び順の鍵 (`setlist_items.position`)。表示用の番号ではない。
 */
position: number, 
/**
 * アンコール等の区切り。
 */
section: string | null, notes: string | null, 
/**
 * `setlist_items.unit_name`。**この披露限りの表記**で、曲のユニットとは別物。
 */
unitLabel: string | null, song: Ref, 
/**
 * 歌唱メンバー。`display_name` は**コアが現任 CV で解決済み**。
 */
performers: Array<PerformerRef>, 
/**
 * 原唱者 (`song_artists.role = 'original'`)。
 */
originalArtists: Array<Ref>, 
/**
 * `songs.song_type == "cover"`。
 */
isCover: boolean, };
