// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * セトリの詳しさ 1 つぶん。
 */
export type SetlistDisplayOptionDto = { 
/**
 * localStorage に残す値。iOS/Android の保存値と同じ文字列。
 */
raw: string, label: string, 
/**
 * 既定のモードか (`SetlistDisplayMode::default_mode`)。1 つだけが真。
 */
isDefault: boolean, };
