// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SetlistRow } from "./SetlistRow";

/**
 * セトリの 1 区切り。`label` が無いのは区切り無し (本編)。
 *
 * 先頭の塊は見出し無しが普通。合同ライブでは見出し付きの塊と無しの塊が交互に来る
 * ので、2 つ目以降の見出し無しも「前の塊の続き」ではなく別の塊として届く。
 */
export type SetlistSection = { 
/**
 * `アンコール` / `LL` など。綴り揺れ (`encore` / `ENCORE`) は畳んである。
 */
label: string | null, rows: Array<SetlistRow>, };
