// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * セトリ行に添える衣装。
 */
export type SetlistCostume = { id: string, name: string, 
/**
 * 誰のための衣装か。共通衣装なら `None`。
 */
attribution: string | null, 
/**
 * その曲でこの衣装を着ていた人。共通衣装なら `None`。
 */
wearersLabel: string | null, };
