// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LineupNote } from "./LineupNote";
import type { PerformerRef } from "./PerformerRef";
import type { Ref } from "./Ref";

/**
 * セトリの 1 行。
 */
export type SetlistRow = { id: string, 
/**
 * **公演内で何曲目か (1 始まり)。画面に出す番号はこちら。**
 *
 * [`Self::position`] は `setlist_items` 全体を通した並び順の値で、実データでは
 * 11593 のような大きな数になる。並べ替えの鍵としては正しいが、そのまま番号として
 * 描くと読めない。どちらを出すかは表示の判断なので、Rust 側で決めておく。
 * 区切り (アンコール) をまたいでも通しで数える。
 */
number: number, notes: string | null, 
/**
 * `setlist_items.unit_name`。**この披露限りの表記**で、曲のユニットとは別物。
 */
unitLabel: string | null, song: Ref, 
/**
 * 歌唱メンバー。`display_name` は**コアが現任 CV で解決済み**。
 */
performers: Array<PerformerRef>, 
/**
 * 公演の出演者全員で歌う行なら `全員`。
 * 判定 (出演者 2 人以上・歌唱者と完全一致) は `domain::setlist_lineup::is_full_cast`。
 * 名前を全部並べる代わりにこの札を出し、名前は畳んでおく。
 */
fullCastLabel: string | null, 
/**
 * 原唱者 (オリメン) との関係。判定できない行・当たり前の行 (ソロ曲を本人が歌う) ・
 * 全員曲の部分一致には付かない。規則は `domain::setlist_lineup::lineup_note`。
 */
lineup: LineupNote | null, 
/**
 * `songs.song_type == "cover"` (曲そのものがカバー曲)。
 */
isCover: boolean, 
/**
 * この披露がその曲の初披露 (この DB に載っている範囲で最古) なら「初披露」。
 */
firstPerformanceLabel: string | null, };
