// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * セトリ行に添えるチップ 1 個ぶんの衣装。
 */
export type SetlistCostume = { id: string, 
/**
 * チップに出す 1 行 (`衣装名` / `衣装名（着ていた人）`)。
 *
 * **名前と着用者を繋ぐのは Rust の仕事。** 出面で組み直すと、括弧の付け方が
 * iOS / Android / Web で割れる (`domain::costume_queries` が唯一の規則)。
 */
label: string, };
