// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SetlistNote } from "./SetlistNote";

/**
 * 行に添える事実の軸 1 本 (`披露` / `歌唱`)。
 */
export type SetlistNoteGroup = { 
/**
 * 行の左に固定幅で出す軸の名前。
 */
label: string, notes: Array<SetlistNote>, };
