// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppOpen } from "./AppOpen";
import type { Ref } from "./Ref";
import type { SeoBlock } from "./SeoBlock";
import type { SetlistRow } from "./SetlistRow";
import type { ShowCostume } from "./ShowCostume";

/**
 * `/shows/<id>/` の中身。
 */
export type ShowPage = { schemaVersion: number, 
/**
 * キャラライブか (`shows.performer_type == "character"`)。
 * 歌唱者の表示モード「公演に合わせる」がこれを見る。
 */
isCharacterLive: boolean, id: string, path: string, name: string, date: string, shortDate: string, themeKey: string, event: Ref, brand: Ref | null, venueLabel: string | null, venue: Ref | null, venueCity: string | null, hall: string | null, startTime: string | null, streamPlatform: string | null, 
/**
 * position 昇順。
 */
setlist: Array<SetlistRow>, 
/**
 * `show_cast` (sort_order 順)。
 */
cast: Array<Ref>, 
/**
 * この公演で着られた衣装 (進行順)。記録が無ければ空。
 */
costumes: Array<ShowCostume>, 
/**
 * 同一ライブ内の他公演 (前後移動用。自分自身も含む)。
 */
siblingShows: Array<Ref>, app: AppOpen, seo: SeoBlock, };
