// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateBadge } from "./DateBadge";
import type { Ref } from "./Ref";

/**
 * 公演 1 件の要約 (ライブ詳細・会場詳細・トップの「最近の公演」で使い回す)。
 *
 * **並べる場所によって見出しが変わる。** ライブ詳細の中では公演名が見出しで、
 * ライブの外 (トップ・会場) ではライブ名が見出しになり、公演名は [`Self::show_label`]
 * として副題へ回る。どちらの文脈かは JSON を作る側 (`emit::events::ShowContext`) が
 * 決めていて、TS は来た形を置くだけ。
 */
export type ShowSummary = { ref: Ref, 
/**
 * 行の見出し (文脈によって公演名かライブ名)。
 */
title: string, 
/**
 * 公演名からライブ名と重なる部分を落としたもの (`DAY1`)。ライブ名を見出しにする
 * 文脈で副題に置く。ライブ詳細の中 (見出しが公演名) では `None`、
 * 公演名がライブ名そのものでも `None` (同じ名前を 2 行続けない)。
 * 規則は披露履歴の `placeDisplay` と同じ `distinguishing_show_name`。
 */
showLabel: string | null, date: string, 
/**
 * 行の左端に置く日付ブロック。
 */
dateBadge: DateBadge, 
/**
 * `shows.venue_label` (会場マスタに紐付かない自由記述もある)。
 * **会場詳細の中では `None`** (全行その会場なので繰り返さない)。
 */
venueLabel: string | null, hall: string | null, 
/**
 * `17:30 開演`。
 */
startTimeDisplay: string | null, setlistCount: number, };
