// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppOpen } from "./AppOpen";
import type { ProfileRow } from "./ProfileRow";
import type { Ref } from "./Ref";
import type { SeoBlock } from "./SeoBlock";
import type { SetlistRow } from "./SetlistRow";

/**
 * `/shows/<id>/` の中身。
 */
export type ShowPage = { schemaVersion: number, 
/**
 * キャラライブか (`shows.performer_type == "character"`)。
 * 歌唱者の表示モード「公演に合わせる」がこれを見る。
 */
isCharacterLive: boolean, id: string, path: string, name: string, 
/**
 * 公演名からライブ名と重なる部分を落としたもの (`Day2` / `昼公演`)。
 *
 * ページの見出しに使う。ライブ名は小見出し (パンくず) が担うので、見出しに
 * ライブ名を丸ごと繰り返さない。公演名がライブ名そのものなら `None`
 * (その場合は見出しに公演名をそのまま出し、小見出しを省く)。
 * 規則は `<title>` や「他の公演」のチップと同じ `distinguishing_show_name`。
 */
shortName: string | null, date: string, themeKey: string, event: Ref, brand: Ref | null, venueCity: string | null, 
/**
 * ヒーローに置く「事実の並び」(日程・開演・会場・ホール・配信)。
 * どの行を出すか・順・見出し・会場へのリンクはここで決めてある。
 * 曲の `fact_rows` / アイドルの `profile_rows` と同じ形。
 */
factRows: Array<ProfileRow>, 
/**
 * position 昇順。
 */
setlist: Array<SetlistRow>, 
/**
 * `show_cast` (sort_order 順)。
 */
cast: Array<Ref>, 
/**
 * 同一ライブ内の他公演 (前後移動用。自分自身も含む)。
 */
siblingShows: Array<Ref>, app: AppOpen, seo: SeoBlock, };
