// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppOpen } from "./AppOpen";
import type { DateBadge } from "./DateBadge";
import type { ProfileRow } from "./ProfileRow";
import type { Ref } from "./Ref";
import type { SeoBlock } from "./SeoBlock";
import type { SetlistSection } from "./SetlistSection";
import type { ShowCostume } from "./ShowCostume";
import type { StatTile } from "./StatTile";

/**
 * `/shows/<id>/` の中身。
 */
export type ShowPage = { schemaVersion: number, 
/**
 * キャラライブか (`shows.performer_type == "character"`)。
 * 歌唱者の表示モード「公演に合わせる」がこれを見る。
 */
isCharacterLive: boolean, id: string, path: string, 
/**
 * ページの見出し。ふつうは**ライブ名** — 公演の主はライブで、`Day2` は見分けでしかない。
 *
 * 公演名がライブ名を丸ごと含む稀な形 (`★グランドフィナーレ★(… Live Broadcast)`) では
 * 公演名そのものが見出しになり、`show_label` は無い。規則は `<title>` と同じ。
 */
heading: string, 
/**
 * 見出しに添える公演の見分け (`Day2` / `昼公演`)。公演名からライブ名と重なる部分を
 * 落としたもので、規則は「他の公演」のチップと同じ `distinguishing_show_name`。
 * 公演名がライブ名そのものなら `None`。
 */
showLabel: string | null, 
/**
 * ヒーローに置く日付ブロック (月日・曜日・年)。
 */
dateBadge: DateBadge, 
/**
 * これから開催される公演か (`開催予定` の札)。境界は一覧の年グループと同じ規則。
 */
isUpcoming: boolean, themeKey: string, event: Ref, brand: Ref | null, 
/**
 * ヒーローに置く「事実の並び」(開演・会場・ホール・所在地・配信)。
 * 日程は `date_badge` が持つのでここには無い。どの行を出すか・順・見出し・
 * 会場へのリンクはここで決めてある。曲の `fact_rows` と同じ形。
 */
factRows: Array<ProfileRow>, 
/**
 * 数の帯 (曲数・出演者)。0 は落としてある。
 */
statTiles: Array<StatTile>, 
/**
 * セトリ。区切り (本編 / アンコール / 合同ライブのブロック) ごとの塊で、
 * 塊の中は position 昇順。塊の切り方と見出しの畳み方は
 * `domain::setlist_sections` が持つ。
 */
setlistSections: Array<SetlistSection>, 
/**
 * `show_cast` (sort_order 順)。
 */
cast: Array<Ref>, 
/**
 * この公演で着られた衣装 (進行順)。記録が無ければ空。
 */
costumes: Array<ShowCostume>, 
/**
 * 同一ライブ内の他公演 (前後移動用。自分自身も含む)。
 */
siblingShows: Array<Ref>, app: AppOpen, seo: SeoBlock, };
