// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 公演で着られた衣装 1 着。
 *
 * **画像は無い。** 版権物を配らない方針なので、名前と出典だけで見分ける。
 */
export type ShowCostume = { id: string, name: string, 
/**
 * 誰のための衣装か (ユニット名・アイドル名)。共通衣装なら `None`。
 */
attribution: string | null, description: string | null, 
/**
 * 出典 (公式)。
 */
sourceUrl: string | null, 
/**
 * どこで着たか (「1・5 曲目」「公演のどこか」)。
 *
 * **文にするのは Rust の仕事。** 曲番号の列を持たせて出面で繋ぐと、
 * 区切りも「どこかで着た」の言い方も画面ごとに割れる。
 */
whereLabel: string, 
/**
 * 着ていた人の 1 行。共通衣装なら `None` (「全員」とは書かない)。
 */
wearersLabel: string | null, };
