// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 公演 1 件ぶんのアイドル id 列。
 *
 * `HashMap` をそのまま serde しないのは、反復順が非決定でバイト一致の再現性を
 * 壊すため (T9)。
 */
export type ShowIdolIds = { showId: string, idolIds: Array<string>, };
