// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ref } from "./Ref";

/**
 * 公演 1 件の要約 (ライブ詳細・会場詳細・トップの「最近の公演」で使い回す)。
 */
export type ShowSummary = { ref: Ref, date: string, 
/**
 * `short_year_month::short_year_month(date)` の結果。
 */
shortDate: string, 
/**
 * `shows.venue_label` (会場マスタに紐付かない自由記述もある)。
 */
venueLabel: string | null, venue: Ref | null, hall: string | null, startTime: string | null, setlistCount: number, streamPlatform: string | null, 
/**
 * ライブ名 (会場ページなど、ライブの外から公演を並べるときに要る)。
 */
event: Ref | null, 
/**
 * 行の副題。
 *
 * **並べる場所によって中身が変わる**: ライブ詳細では親ライブ名が自明なので入らず、
 * トップと会場詳細では入る。出し分けは JSON を作る側で済ませてあるので、
 * TS は文脈を見ずにそのまま描いてよい ([`Self::event`] の有無と対応する)。
 */
subtitle: string | null, };
