// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ForecastRow } from "./ForecastRow";

/**
 * セトリの機械予測 (`domain::setlist_forecast`。アプリの予想と同じモデル)。
 */
export type ShowForecast = { title: string, 
/**
 * 何をどう並べたかの一言 (機械的な目安であること)。
 */
lede: string, songs: Array<ForecastRow>, 
/**
 * 精度についての注記 (出演者未発表など)。
 */
notes: Array<string>, };
