// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 同じライブの公演の行き来の形。
 *
 * 数本ならヒーローの中の帯 (DAY1 / DAY2 と行き来するのが一番多い操作)。ツアーのように
 * 多いと横に並べきれないので前後への送りにし、全部の並びは脇に置く。単日公演は無し。
 */
export type SiblingNav = "hidden" | "segments" | "pager";
