// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ref } from "./Ref";

/**
 * 「よく歌う人」の 1 行。
 */
export type SingerRow = { idol: Ref, 
/**
 * この人が歌った回数。
 */
times: number, 
/**
 * 分母 (この曲の披露回数)。
 */
total: number, };
