// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * サイトの一覧への入口 1 枚 (記号・名前・ひとこと・行き先)。
 */
export type SiteEntry = { glyph: string, title: string, preview: string, path: string, };
