// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppLinks } from "./AppLinks";
import type { Counts } from "./Counts";
import type { PerformerNameOptionDto } from "./PerformerNameOptionDto";

/**
 * サイト全体のメタ (`meta.json`)。
 */
export type SiteMeta = { schemaVersion: number, 
/**
 * RFC3339 UTC。`--today` から導出する (`YYYY-MM-DDT00:00:00Z`)。
 * 実時刻を入れないのは、同じ入力で 2 回流したときに出力がバイト一致する
 * (= 再現性がある) ことをテストで固定したいから。
 */
generatedAt: string, 
/**
 * JST の「今日」。upcoming / past の分割はすべてこの 1 個から決まる。
 * Astro もブラウザも `Date` を触らない。
 */
todayJst: string, dataVersion: string | null, contentHash: string | null, counts: Counts, app: AppLinks, 
/**
 * セトリの歌唱者をどの名前で出すかの選択肢 (順・保存値・文言)。
 *
 * **アプリと同じ 1 本** (`domain::event_detail_queries::performer_name_options`)。
 * 出面が独自にラベルを持つと、アプリの設定画面と文言がズレる。
 */
performerNameOptions: Array<PerformerNameOptionDto>, };
