// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppLinks } from "./AppLinks";
import type { Counts } from "./Counts";
import type { NavLink } from "./NavLink";
import type { PerformerNameOptionDto } from "./PerformerNameOptionDto";

/**
 * サイト全体のメタ (`meta.json`)。
 */
export type SiteMeta = { schemaVersion: number, 
/**
 * RFC3339 UTC。`--today` から導出する (`YYYY-MM-DDT00:00:00Z`)。
 * 実時刻を入れないのは、同じ入力で 2 回流したときに出力がバイト一致する
 * (= 再現性がある) ことをテストで固定したいから。
 */
generatedAt: string, 
/**
 * JST の「今日」。upcoming / past の分割はすべてこの 1 個から決まる。
 * Astro もブラウザも `Date` を触らない。
 */
todayJst: string, dataVersion: string | null, contentHash: string | null, counts: Counts, app: AppLinks, 
/**
 * セトリの歌唱者をどの名前で出すかの選択肢 (順・保存値・文言)。
 *
 * **アプリと同じ 1 本** (`domain::event_detail_queries::performer_name_options`)。
 * 出面が独自にラベルを持つと、アプリの設定画面と文言がズレる。
 */
performerNameOptions: Array<PerformerNameOptionDto>, 
/**
 * サイト共通ナビの並び (ヘッダとフッタが同じ 1 本を描く)。
 *
 * **お題 (`/polls/`) は焼き込んだ集計が空だと書き出されない**ので、
 * 出す/出さないを知っているのは JSON を作る側だけ。TS に手書きの一覧を
 * 持たせると、その条件を知らないままリンク切れを出す。
 */
primaryNav: Array<NavLink>, 
/**
 * 一覧以外の入口 (検索・このサイトについて)。フッタが描く。
 * 全ページのクロームに載るリンクはすべて `meta.json` にある = 到達性の起点。
 */
utilityNav: Array<NavLink>, 
/**
 * フッタの断り書き (非公式表記・載せていないもの)。文面は `content::footer_notes`。
 */
footerNotes: Array<string>, 
/**
 * 歌詞掲載の許諾表示 (`JASRAC 許諾番号 …`)。出面で歌詞を出すときだけ入り、
 * フッタが許諾マークの隣に描く (掲示が許諾の条件)。
 */
lyricsLicenseNotice: string | null, 
/**
 * 歌詞の中の言葉で曲を探す API (検索ページの「歌詞」が押されたときだけ叩く)。
 * 出面で歌詞を出すときだけ入る。TS は URL を組まず、ここに来たものを使う。
 */
lyricsSearchUrl: string | null, };
