// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 一覧の絞り込み条件を、**出面 (JSON) で運ぶための形**。
 *
 * `SongListFilter` + 並べ替え。ページを組んだ Rust が土台として書き出し、
 * ブラウザの wasm がそのまま読んで `song_list_indexes` を回す。
 *
 * **これが Rust ↔ wasm ↔ TS の唯一の定義**。以前は
 * (a) `emit::lists::query_base_json` の手書き camelCase JSON、
 * (b) wasm 側の写し、(c) TS の手書き interface、と 3 つに割れていて、
 * 軸を 1 本足すと 3 箇所を人手で揃える必要があった (型でもテストでも捕まらない)。
 *
 * ts-rs は `web-export` のときだけ付く。wasm 側はこの型を素の serde で読む。
 */
export type SongQuery = { brandIds: Array<string>, title: string | null, idolName: string | null, idolIds: Array<string>, songwriter: string | null, cdSeries: string | null, seriesGroup: string | null, liveName: string | null, songType: string | null, includeRemixes: boolean, includeOtherBrand: boolean, excludeLiveOnly: boolean, 
/**
 * `SongListSort::key()` の値。未知の鍵は既定 (50 音順) に倒れる。
 */
sort: string, 
/**
 * 省略時はその並びの既定方向 (`SongListSort::default_ascending`)。
 */
ascending: boolean | null, };
