// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SongFacetValue } from "./SongFacetValue";

/**
 * 絞り込みの 1 軸。
 */
export type SongFacet = { key: string, label: string, 
/**
 * 複数選んだときに OR で結ぶか (false = 単一選択)。
 */
multi: boolean, values: Array<SongFacetValue>, 
/**
 * 行 i がこの軸で持つ値の添字列 (`values` への index)。
 * 原唱者・イベントのような多値の軸があるので、単値の軸でも列で持つ。
 */
rowValues: Array<Array<number>>, };
