// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KanaSection } from "./KanaSection";
import type { NavLink } from "./NavLink";
import type { Ref } from "./Ref";
import type { SeoBlock } from "./SeoBlock";
import type { SongListItem } from "./SongListItem";
import type { SongListKind } from "./SongListKind";

/**
 * 楽曲一覧ページ。`/songs/` `/songs/brand/<brandId>/` `/songs/all/`。
 */
export type SongListPage = { schemaVersion: number, path: string, title: string, kind: SongListKind, brand: Ref | null, items: Array<SongListItem>, 
/**
 * よみの先頭 1 文字で切った目次。
 */
kanaSections: Array<KanaSection>, brandLinks: Array<NavLink>, total: number, seo: SeoBlock, };
