// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PenlightSetDto } from "./PenlightSetDto";
import type { TagChipDto } from "./TagChipDto";

/**
 * 曲のコミュニティ集計。ページに出すのはここにあるものだけ。
 */
export type SongCommunity = { tags: Array<TagChipDto>, 
/**
 * お気に入りに入れている人の数。
 */
favorites: number, 
/**
 * ペンライトの色セット (得票の多い順)。
 */
penlight: Array<PenlightSetDto>, };
