// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppOpen } from "./AppOpen";
import type { CoOccurRow } from "./CoOccurRow";
import type { CreditGroup } from "./CreditGroup";
import type { PerformanceRow } from "./PerformanceRow";
import type { Ref } from "./Ref";
import type { SeoBlock } from "./SeoBlock";
import type { SingerRow } from "./SingerRow";

/**
 * `/songs/<id>/` の中身。
 *
 * **ページは全曲ぶん作る** (派生曲・`other` ブランドを含む)。共有リンクや検索から
 * 到達できるべきだから。一覧に載せるかどうかだけが `SongListFilter` の判断。
 */
export type SongPage = { schemaVersion: number, id: string, path: string, title: string, titleKana: string | null, themeKey: string, brand: Ref | null, songType: string | null, releaseDate: string | null, durationSec: number | null, 
/**
 * `"4:32"`。整形だけなのでここで作る。
 */
durationDisplay: string | null, 
/**
 * `credit_names::split_credits` 済み。
 */
credits: Array<CreditGroup>, cdSeries: string | null, cdTitle: string | null, seriesGroup: string | null, 
/**
 * Apple Music CDN。サイト唯一の外部画像。
 */
artworkUrl: string | null, appleMusicUrl: string | null, jasracCode: string | null, originalArtists: Array<Ref>, otherArtists: Array<Ref>, unit: Ref | null, 
/**
 * `songs.unit_name` (マスタに無いユニット表記)。
 */
unitLabel: string | null, 
/**
 * 派生曲の親。
 */
parent: Ref | null, 
/**
 * この曲の派生 (リミックス・ソロver 等)。
 */
variants: Array<Ref>, performanceCount: number, 
/**
 * date 降順。
 */
performanceHistory: Array<PerformanceRow>, frequentSingers: Array<SingerRow>, coOccurring: Array<CoOccurRow>, related: Array<Ref>, app: AppOpen, seo: SeoBlock, 
/**
 * 歌詞は Web に載せない。この固定文だけを出す。
 * JASRAC 許諾を持つのは**アプリ**であって本サイトではない、という主語を崩さないこと。
 */
lyricsNote: string, };
