// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SongFacet } from "./SongFacet";
import type { SongListOrder } from "./SongListOrder";

/**
 * 一覧を絞り込む/並べ替えるための素材。`index/songs-filter*.json`。
 *
 * **軸も値も並び順も決めるのは Rust**で、受け手 (ブラウザ) がやるのは
 * (1) 選ばれた値の集合一致、(2) 渡された順列を当てる、の 2 つだけ。
 * 照合規則・並び順の規則を TS に持たせないための形 (INV-1)。
 * 名前での絞り込みだけは任意の入力なので事前計算できず、`imas-text-fold` の
 * wasm (アプリと同じ規則) が `haystacks` に対して判定する。
 *
 * 一覧の HTML とは別ファイルにして、絞り込みを開いた人だけが取りに行く。
 * 行は `SongListPage.items` と同じ並び・同じ添字。
 */
export type SongListFilterData = { schemaVersion: number, 
/**
 * どの一覧のものか (`/songs/` `/songs/brand/<id>/`)。
 */
path: string, rowCount: number, facets: Array<SongFacet>, orders: Array<SongListOrder>, 
/**
 * フィールドの区切り。**JSON に明示して配る** (JS 側に定数を持たせない)。
 */
separator: string, 
/**
 * 行ごとの照合対象。`Snapshot` が組んだ検索索引の畳み済みフィールドを
 * `separator` で連ねたもの。ブラウザは検索語だけを同じ規則で畳んで
 * 部分一致を見る (`/search/` と同じ照合)。
 */
haystacks: Array<string>, };
