// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ref } from "./Ref";

/**
 * 楽曲一覧の 1 行。
 */
export type SongListItem = { ref: Ref, releaseDate: string | null, unitLabel: string | null, 
/**
 * 原唱者を 1 行に畳んだもの (`join_capped` で「先頭 4 名 ほか N 名」に丸めた形)。
 *
 * `subtitle` にも畳み込まれているが、表形式の一覧は列に分けて出すので
 * 独立して持つ。**丸め方を決めるのはここ (Rust) の 1 箇所**で、
 * 受け手が名前の配列から組み立て直すことはしない。
 */
artistsLabel: string | null, 
/**
 * 披露回数。
 *
 * `/songs/all/` (全件ハブ) では **`None`**。あちらは 3,153 行を 1 枚に並べる
 * 到達性のためのページなので、行に付ける情報を `ref` だけまで削ってある。
 * `0` ではなく `None` にしてあるのは、「0 回披露」と「載せていない」を
 * 取り違えないようにするため。
 */
performanceCount: number | null, 
/**
 * 行の副題 (ユニット名・原唱者・リリース日)。空なら `None`。
 */
subtitle: string | null, };
