// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ref } from "./Ref";

/**
 * 楽曲一覧の 1 行。
 */
export type SongListItem = { ref: Ref, releaseDate: string | null, unitLabel: string | null, 
/**
 * 披露回数。
 *
 * `/songs/all/` (全件ハブ) では **`None`**。あちらは 3,153 行を 1 枚に並べる
 * 到達性のためのページなので、行に付ける情報を `ref` だけまで削ってある。
 * `0` ではなく `None` にしてあるのは、「0 回披露」と「載せていない」を
 * 取り違えないようにするため。
 */
performanceCount: number | null, 
/**
 * 行の副題 (ユニット名・原唱者・リリース日)。空なら `None`。
 */
subtitle: string | null, };
