// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KanaSection } from "./KanaSection";
import type { NavLink } from "./NavLink";
import type { Ref } from "./Ref";
import type { SeoBlock } from "./SeoBlock";
import type { SongListItem } from "./SongListItem";
import type { SongListKind } from "./SongListKind";

/**
 * 楽曲一覧ページ。`/songs/` `/songs/brand/<brandId>/` `/songs/all/`。
 */
export type SongListPage = { schemaVersion: number, path: string, title: string, kind: SongListKind, brand: Ref | null, items: Array<SongListItem>, 
/**
 * 行を `ref` だけまで削った一覧か (`/songs/all/`)。
 *
 * **行から何を落としたかを決めるのは Rust の 1 箇所**なので、受け手は
 * 行を走査して列の有無を推測しない (走査すると「たまたま全行 null」と
 * 「そもそも載せていない」が混ざり、同じ種類のページで表の形が変わる)。
 */
rowsAreLight: boolean, kanaSections: Array<KanaSection>, brandLinks: Array<NavLink>, 
/**
 * 既定フィルタから外れた曲も含む全件ハブ (`/songs/all/`) への案内。
 *
 * `/songs/` にだけ入る。これが無いと、一覧規則で外れた曲 (派生曲・ライブ限定曲・
 * `other` ブランド) の詳細ページが `/` からどこからも辿れなくなる。
 */
allSongsLink: NavLink | null, total: number, seo: SeoBlock, };
