// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppOpen } from "./AppOpen";
import type { CoOccurRow } from "./CoOccurRow";
import type { CreditGroup } from "./CreditGroup";
import type { EmptyText } from "./EmptyText";
import type { LinkedNote } from "./LinkedNote";
import type { LyricsBlock } from "./LyricsBlock";
import type { PerformanceRow } from "./PerformanceRow";
import type { ProfileRow } from "./ProfileRow";
import type { Ref } from "./Ref";
import type { SeoBlock } from "./SeoBlock";
import type { SingerRow } from "./SingerRow";
import type { SongCommunity } from "./SongCommunity";
import type { StatTile } from "./StatTile";

/**
 * `/songs/<id>/` の中身。
 *
 * **ページは全曲ぶん作る** (派生曲・`other` ブランドを含む)。共有リンクや検索から
 * 到達できるべきだから。一覧に載せるかどうかだけが `SongListFilter` の判断。
 */
export type SongPage = { schemaVersion: number, id: string, path: string, title: string, titleKana: string | null, themeKey: string, brand: Ref | null, 
/**
 * 合同曲で一緒に参加しているブランド (`brand` 以外)。無ければ空。
 */
jointBrands: Array<Ref>, 
/**
 * 合同曲の札 (`content::SONG_COLLAB_LABEL`)。合同曲でなければ `None`。
 */
collabLabel: string | null, 
/**
 * KAMISABI の収録札 (`content::SONG_KAMISABI_LABEL`)。収録でなければ `None`。
 */
kamisabiLabel: string | null, 
/**
 * 曲の補足 (自由文、例: 「ミリシタ 1 周年記念楽曲」)。無ければ `None`。
 */
note: string | null, 
/**
 * コミュニティ集計 (タグ・お気に入り・ペンライト)。焼き込み。
 */
community: SongCommunity, 
/**
 * 「みんなの記録」の節を出すか (タグ・お気に入り・ペンライトのどれかがある)。
 */
hasCommunity: boolean, 
/**
 * 歌詞・コールガイドの出し方。**出すかどうかを決めるのは Rust。**
 */
lyrics: LyricsBlock, 
/**
 * 曲種別の表示名 (`全体曲` / `ソロ曲` …)。語彙に無い値なら `None`。
 */
songTypeLabel: string | null, releaseDate: string | null, 
/**
 * `credit_names::split_credits` 済み。
 */
credits: Array<CreditGroup>, 
/**
 * Apple Music CDN。サイト唯一の外部画像。
 */
artworkUrl: string | null, appleMusicUrl: string | null, originalArtists: Array<Ref>, otherArtists: Array<Ref>, unit: Ref | null, 
/**
 * `songs.unit_name` (マスタに無いユニット表記)。
 */
unitLabel: string | null, 
/**
 * 派生曲の親を言う 1 文 (`この曲は <親> の派生曲です。`)。派生曲でなければ `None`。
 */
parentNote: LinkedNote | null, 
/**
 * この曲の派生 (リミックス・ソロver 等)。
 */
variants: Array<Ref>, performanceCount: number, 
/**
 * 数の帯 (披露回数 / 原唱者 / 派生曲)。ページ内の該当の節へ飛ぶ。
 */
statTiles: Array<StatTile>, 
/**
 * date 降順。
 */
performanceHistory: Array<PerformanceRow>, 
/**
 * 披露の記録が 1 件も無いときの案内。
 */
historyEmpty: EmptyText | null, frequentSingers: Array<SingerRow>, coOccurring: Array<CoOccurRow>, related: Array<Ref>, 
/**
 * 「基本情報」の行 (リリース・収録・シリーズ・再生時間・JASRAC 作品コード)。
 *
 * アイドルの `profile_rows` と同じ形。**どの項目をどの順で出すか / 値が無い行を
 * 落とすか**の判断はここで済ませてあるので、web は上から並べるだけでよい。
 */
factRows: Array<ProfileRow>, app: AppOpen, seo: SeoBlock, };
