// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FacetOption } from "./FacetOption";
import type { SortOption } from "./SortOption";

/**
 * 楽曲一覧の選択肢。
 */
export type SongFacets = { 
/**
 * 一覧に実際に居るアイドルのブランドだけ (外部ゲストしか居ない `other` は出さない)。
 */
brands: Array<FacetOption>, idols: Array<FacetOption>, cdSeries: Array<FacetOption>, seriesGroups: Array<FacetOption>, 
/**
 * 曲種別。一覧に実在する種別だけを、`vocabulary::SONG_TYPES` の並びと正式な形で (Q-08f)。
 */
songTypes: Array<FacetOption>, 
/**
 * ログインもユーザーデータも持たない出面で選べる並べ替え。
 */
sorts: Array<SortOption>, 
/**
 * 既定の並べ替え (未指定・未知の鍵が倒れる先)。
 */
defaultSort: string, };
