// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 並べ替えの 1 種。
 *
 * **昇順と降順の両方を持つ。** 受け手が片方を反転すると、同着の並び
 * (五十音での安定化) まで裏返ってアプリと違う並びになる。
 */
export type SongListOrder = { key: string, label: string, defaultAscending: boolean, 
/**
 * `items` の添字の順列。
 */
ascending: Array<number>, descending: Array<number>, };
