// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 並べ替え 1 件。既定の向きもここが持つ (出面は矢印の初期値に使う)。
 */
export type SortOption = { 
/**
 * `SongListSort::key` / `IdolSortKind::key`。
 */
key: string, label: string, defaultAscending: boolean, };
