// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 件数タイル 1 枚。
 *
 * どの件数を、どの順で、どのラベルとグリフで出すかは**そのページの意味の判断**なので
 * Rust が決める。`Counts` を素で配って .astro が表を組むと、同じ表が画面ごとに
 * コピーされ、実際にトップ 6 件・About 7 件・ブランド 4 件で中身が食い違っていた。
 */
export type StatTile = { 
/**
 * 見出しの記号 (`♪` `▤` `♬` …)。版権物を持たないので記号で見分ける。
 */
glyph: string, value: number, label: string, 
/**
 * 一覧への入口。押せないタイルは `None`。
 */
href: string | null, };
