// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * タグの素性 (名前・色・公式か)。札の見た目はこれだけで決まる。
 * 曲ページの札 ([`TagChipDto`]) は これに件数と押し先を足したもの。
 */
export type TagBadge = { id: string, name: string, 
/**
 * タグ自身の色 (hex)。無ければ受け手が既定色で出す。
 */
color: string | null, 
/**
 * 運営が用意したタグか。
 */
isOfficial: boolean, };
