// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * タグの素性 (名前・色・公式か)。札の見た目はこれだけで決まる。
 * 曲ページの札 ([`TagChipDto`]) は これに件数と押し先を足したもの。
 */
export type TagBadge = { id: string, name: string, 
/**
 * `themes.css` のキー (`tag:<id>`)。自分の色を持つタグにだけ入る。
 * 無ければ `data-theme` を置かず、囲む要素のテーマ (曲・アイドルの色) を継ぐ。
 */
themeKey: string | null, 
/**
 * 運営が用意したタグか。
 */
isOfficial: boolean, };
