// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * コミュニティが付けたタグ 1 件。
 *
 * **この出面は読むだけ。** 付ける/外すはログインが要るのでアプリへ誘導する。
 */
export type TagChipDto = { id: string, name: string, 
/**
 * 何人が付けたか。
 */
count: number, 
/**
 * タグ自身の色 (hex)。無ければ受け手が既定色で出す。
 */
color: string | null, 
/**
 * 運営が用意したタグか。
 */
isOfficial: boolean, };
