// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SeoBlock } from "./SeoBlock";
import type { TagListItem } from "./TagListItem";

/**
 * タグ一覧ページ。`/tags/`。曲に付いたコミュニティのタグを、付いている曲の多い順に並べる。
 *
 * **読むだけ。** タグ付けはログインが要るのでアプリへ誘導する。集計は `db/community.sql`
 * を焼き込んだもので、閲覧のたびに D1 は読まない。
 */
export type TagListPage = { schemaVersion: number, path: string, title: string, 
/**
 * 見出しの下の説明。
 */
lede: string, items: Array<TagListItem>, total: number, seo: SeoBlock, };
