// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TagChipDto } from "./TagChipDto";

/**
 * タグ一覧の 1 行。
 */
export type TagListItem = { 
/**
 * 札 (`path` はそのタグの曲一覧、`count` は付けた人の延べ数)。
 */
tag: TagChipDto, description: string | null, 
/**
 * 運営が用意したタグに付く札 (`content::TAG_OFFICIAL_LABEL`)。
 */
officialLabel: string | null, 
/**
 * 付いている曲の数。
 */
songCount: number, };
