// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TagBadge } from "./TagBadge";

/**
 * タグ一覧の 1 行。
 */
export type TagListItem = { badge: TagBadge, 
/**
 * そのタグの曲一覧 (`/tags/<tagId>/`)。
 */
path: string, description: string | null, 
/**
 * 運営が用意したタグに付く札 (`content::TAG_OFFICIAL_LABEL`)。
 */
officialLabel: string | null, 
/**
 * 付いている曲の数。
 */
songCount: number, };
