// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NavLink } from "./NavLink";
import type { SeoBlock } from "./SeoBlock";
import type { TagChipDto } from "./TagChipDto";
import type { TagSongRow } from "./TagSongRow";

/**
 * タグ 1 つの曲一覧。`/tags/<tagId>/`。付けた人の多い順。
 */
export type TagPage = { schemaVersion: number, path: string, title: string, tag: TagChipDto, 
/**
 * タグ自身の説明 (付けた人が書いたもの)。無ければ `None`。
 */
description: string | null, 
/**
 * 見出しの下の説明 (並び順の断り)。
 */
lede: string, items: Array<TagSongRow>, total: number, 
/**
 * タグ一覧 (`/tags/`) へ戻る導線。
 */
allTagsLink: NavLink, seo: SeoBlock, };
