// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ref } from "./Ref";

/**
 * タグの付いた曲 1 行。
 */
export type TagSongRow = { ref: Ref, 
/**
 * 行の副題 (ユニット名・原唱者・リリース日)。楽曲一覧の行と同じ畳み方。
 */
subtitle: string | null, 
/**
 * 何人が付けたか。
 */
votes: number, 
/**
 * 1 始まりの順位 (同数でも別の順位を振る = 表示の通し番号)。
 */
rank: number, };
