// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThemeTokens } from "./ThemeTokens";

/**
 * 1 テーマぶんのライト / ダーク。
 */
export type ThemePair = { light: ThemeTokens, dark: ThemeTokens, };
