// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThemePair } from "./ThemePair";

/**
 * テーマトークン表 (`themes.json`)。
 *
 * 実際に配るのは Rust が書き出す単一の `themes.css` (`[data-theme="idol:xxx"]{…}`) で、
 * この JSON は **CSS の生成元 + テスト用の突き合わせ材料**として置く。
 * 出面がインライン style を配らないのは、CSP に `unsafe-inline` を要らなくするため。
 */
export type ThemeTable = { schemaVersion: number, 
/**
 * キーは `idol:<idolId>` / `brand:<brandId>` / `neutral`。
 * `BTreeMap` なのは出力をバイト一致で再現するため (`HashMap` を serde しない)。
 */
themes: { [key in string]: ThemePair }, };
