// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * チケット受付 1 件。段階・表示文字列は domain (`ticket_sales`) が決め切ったものをそのまま置く。
 */
export type TicketSaleItem = { id: string, name: string, kindLabel: string, stageLabel: string, 
/**
 * 対象公演の短い名を `・` で結んだもの (`DAY1・DAY2`)。全公演対象なら `None`。
 */
showsLabel: string | null, 
/**
 * `"4/1 (水) 12:00 〜 4/12 (日) 23:59"`。
 */
period: string | null, 
/**
 * `"4/15 (水)"`。当落発表が無ければ `None`。
 */
result: string | null, url: string | null, note: string | null, sourceUrl: string, };
