// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * チケット情報 (列をそのまま写す)。
 */
export type TicketInfo = { openDate: string | null, deadline: string | null, lotteryDate: string | null, url: string | null, };
