// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * チケットの日程 1 行。語は `vocabulary::TICKET_DATES` (Q-08g)。
 */
export type TicketDate = { label: string, 
/**
 * `yyyy-MM-dd` (列の値のまま)。
 */
date: string, };
