// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TicketSaleItem } from "./TicketSaleItem";

/**
 * チケットの案内 (ライブ詳細の脇)。
 */
export type TicketInfo = { 
/**
 * 受付の一覧 (`ticket_sales::sort_sales` と同じ並び)。
 */
sales: Array<TicketSaleItem>, 
/**
 * イベントに紐づく汎用の申込リンク (`events.ticket_url`)。個々の受付の
 * リンクは `TicketSaleItem::url` を見る。
 */
url: string | null, };
