// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TicketDate } from "./TicketDate";

/**
 * チケットの案内 (ライブ詳細の脇)。
 */
export type TicketInfo = { 
/**
 * 日付の入っている日程だけ、受付開始 → 申込締切 → 当落発表 の順。
 */
dates: Array<TicketDate>, url: string | null, };
