// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * チケット受付 1 件。表示文字列は domain (`ticket_sales`) が決め切ったものをそのまま置く。
 *
 * L5: 段階 (`stage_label`) は持たない。Web の公開は日次 (JST 05:00) 固定で、段階は
 * 判定した瞬間で止まったまま一日中変わらないので、時々刻々変わる「受付中」等の札を
 * 静的ページに出さない (期間・当落の日程だけを事実として出す)。
 */
export type TicketSaleItem = { id: string, name: string, kindLabel: string, 
/**
 * 対象公演の短い名を `・` で結んだもの (`DAY1・DAY2`)。全公演対象なら `None`。
 */
showsLabel: string | null, 
/**
 * `"4/1 (水) 12:00 〜 4/12 (日) 23:59"`。
 */
period: string | null, 
/**
 * `"4/15 (水)"`。当落発表が無ければ `None`。
 */
result: string | null, url: string | null, note: string | null, sourceUrl: string, };
