// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TimelineMilestoneMark = { x: number, y: number, dateDisplay: string, label: string, themeKey: string | null, textX: number, 
/**
 * 文字を点の左に右寄せで置くか (右端)。
 */
flip: boolean, dateY: number, labelY: number, };
