// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TimelineYearTick = { year: number, 
/**
 * 目盛りの文字 (幅が狭い年は下 2 桁)。
 */
label: string, x: number, width: number, 
/**
 * 文字の x (年の枠の中央)。
 */
labelX: number, };
