// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TimelineReleaseBar = { year: number, count: number, x: number, y: number, width: number, height: number, labelX: number, labelY: number, };
