// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TimelineLiveDot = { x: number, y: number, r: number, path: string, 
/**
 * ツールチップ (`<title>`) に出す名前と日付。
 */
title: string, featured: boolean, themeKey: string, };
