// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ref } from "./Ref";

/**
 * 今年のライブ 1 行。
 */
export type TimelineLiveRow = { 
/**
 * `9.26`。
 */
dateDisplay: string, event: Ref, 
/**
 * 周年ライブの札。
 */
chip: string | null, };
