// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilterAxis } from "./FilterAxis";
import type { SeoBlock } from "./SeoBlock";
import type { TimelineChartDto } from "./TimelineChartDto";
import type { TimelineLegend } from "./TimelineLegend";
import type { TimelineLiveRow } from "./TimelineLiveRow";
import type { TimelineMilestoneRow } from "./TimelineMilestoneRow";

export type TimelinePage = { schemaVersion: number, path: string, title: string, lede: string, 
/**
 * すべて / ブランドごと の切替。
 */
scope: FilterAxis, chart: TimelineChartDto, 
/**
 * 図の下の凡例 (段の読み方)。
 */
legend: Array<TimelineLegend>, 
/**
 * 今年のライブ (見出しと一覧)。
 */
yearLivesTitle: string, yearLives: Array<TimelineLiveRow>, 
/**
 * 今年の節目。
 */
yearMilestonesTitle: string, yearMilestones: Array<TimelineMilestoneRow>, seo: SeoBlock, };
