// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TimelineLaneBand = { label: string, y: number, height: number, 
/**
 * 段名の文字のベースライン。
 */
labelY: number, };
