// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimelineLaneBand } from "./TimelineLaneBand";
import type { TimelineLiveDot } from "./TimelineLiveDot";
import type { TimelineMilestoneMark } from "./TimelineMilestoneMark";
import type { TimelineReleaseBar } from "./TimelineReleaseBar";
import type { TimelineYearTick } from "./TimelineYearTick";

export type TimelineChartDto = { width: number, height: number, 
/**
 * 段名の欄の右端 (年の罫線はここから)。
 */
gutter: number, rulerHeight: number, years: Array<TimelineYearTick>, lanes: Array<TimelineLaneBand>, milestones: Array<TimelineMilestoneMark>, lives: Array<TimelineLiveDot>, releases: Array<TimelineReleaseBar>, 
/**
 * 今日の縦線。範囲外なら None。
 */
todayX: number | null, };
