// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ref } from "./Ref";

/**
 * ユニット一覧の 1 行。
 */
export type UnitListItem = { ref: Ref, brand: Ref | null, isPermanent: boolean, memberCount: number, songCount: number, };
