// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NavLink } from "./NavLink";
import type { Ref } from "./Ref";
import type { SeoBlock } from "./SeoBlock";
import type { UnitListItem } from "./UnitListItem";

/**
 * ユニット一覧ページ。`/units/` `/units/brand/<brandId>/`。
 */
export type UnitListPage = { schemaVersion: number, path: string, title: string, brand: Ref | null, items: Array<UnitListItem>, brandLinks: Array<NavLink>, total: number, seo: SeoBlock, };
