// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppOpen } from "./AppOpen";
import type { Ref } from "./Ref";
import type { SeoBlock } from "./SeoBlock";
import type { TagChipDto } from "./TagChipDto";

/**
 * `/units/<id>/` の中身。
 */
export type UnitPage = { schemaVersion: number, id: string, path: string, name: string, nameKana: string | null, 
/**
 * 別名 (`units.name_alt`)。
 */
nameAlt: string | null, themeKey: string, 
/**
 * 常設ユニットか (false = ライブ限定などの期間限定)。
 */
isPermanent: boolean, 
/**
 * コミュニティが付けたタグ (多い順)。焼き込み。
 */
tags: Array<TagChipDto>, brand: Ref | null, members: Array<Ref>, songs: Array<Ref>, app: AppOpen, seo: SeoBlock, };
