// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilterAxis } from "./FilterAxis";
import type { KanaSection } from "./KanaSection";
import type { Ref } from "./Ref";
import type { SeoBlock } from "./SeoBlock";
import type { UnitListItem } from "./UnitListItem";

/**
 * ユニット一覧ページ。`/units/` `/units/brand/<brandId>/`。
 */
export type UnitListPage = { schemaVersion: number, path: string, title: string, brand: Ref | null, items: Array<UnitListItem>, 
/**
 * 楽曲一覧と同じ、よみの目次。`items` はよみ順に並んでいる。
 */
kanaSections: Array<KanaSection>, 
/**
 * 畳んだメニューにする軸 (ブランド)。
 */
filters: Array<FilterAxis>, total: number, seo: SeoBlock, };
