// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppOpen } from "./AppOpen";
import type { EmptyText } from "./EmptyText";
import type { Ref } from "./Ref";
import type { SeoBlock } from "./SeoBlock";
import type { TagChipDto } from "./TagChipDto";

/**
 * `/units/<id>/` の中身。
 */
export type UnitPage = { schemaVersion: number, id: string, path: string, name: string, nameKana: string | null, 
/**
 * 別名 (`units.name_alt`)。
 */
nameAlt: string | null, themeKey: string, 
/**
 * その言い方 (「常設ユニット」/「公演限定」)。一覧の札と同じ語 (`content::unit_kind_label`)。
 */
kindLabel: string, 
/**
 * コミュニティが付けたタグ (多い順)。焼き込み。
 */
tags: Array<TagChipDto>, brand: Ref | null, members: Array<Ref>, 
/**
 * メンバーが 1 人も居ないときの案内。
 */
membersEmpty: EmptyText | null, songs: Array<Ref>, 
/**
 * ユニット曲が 1 曲も無いときの案内。
 */
songsEmpty: EmptyText | null, app: AppOpen, seo: SeoBlock, };
