// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilterAxis } from "./FilterAxis";
import type { SeoBlock } from "./SeoBlock";
import type { VenueListItem } from "./VenueListItem";

/**
 * 会場一覧ページ。`/venues/` `/venues/pref/<prefecture>/`。
 */
export type VenueListPage = { schemaVersion: number, path: string, title: string, 
/**
 * 都道府県別のときだけ入る。空欄の会場は `未分類` に集める。
 */
prefecture: string | null, items: Array<VenueListItem>, 
/**
 * 畳んだメニューにする軸 (都道府県)。
 */
filters: Array<FilterAxis>, total: number, seo: SeoBlock, };
