// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppOpen } from "./AppOpen";
import type { HallRow } from "./HallRow";
import type { Ref } from "./Ref";
import type { SeoBlock } from "./SeoBlock";
import type { ShowSummary } from "./ShowSummary";
import type { VenueNameRow } from "./VenueNameRow";

/**
 * `/venues/<id>/` の中身。
 */
export type VenuePage = { schemaVersion: number, id: string, path: string, name: string, nameKana: string | null, themeKey: string, 
/**
 * 都道府県 (文字列。空のものは一覧では `未分類` に集める)。
 */
prefecture: string | null, city: string | null, capacity: number | null, aliases: Array<string>, halls: Array<HallRow>, 
/**
 * 旧称。
 */
pastNames: Array<VenueNameRow>, events: Array<Ref>, shows: Array<ShowSummary>, app: AppOpen, seo: SeoBlock, };
