// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppOpen } from "./AppOpen";
import type { HallRow } from "./HallRow";
import type { ProfileRow } from "./ProfileRow";
import type { Ref } from "./Ref";
import type { SeoBlock } from "./SeoBlock";
import type { ShowSummary } from "./ShowSummary";
import type { VenueNameRow } from "./VenueNameRow";

/**
 * `/venues/<id>/` の中身。
 */
export type VenuePage = { schemaVersion: number, id: string, path: string, name: string, nameKana: string | null, themeKey: string, 
/**
 * 都道府県 (文字列。空のものは一覧では `未分類` に集める)。
 */
prefecture: string | null, city: string | null, 
/**
 * 「千葉県 千葉市美浜区」。都道府県と市区町村の連結を TS に書かせない。
 */
locationDisplay: string | null, capacity: number | null, 
/**
 * 別名を `" ・ "` で繋いだもの。空なら `None`。
 */
aliasesDisplay: string | null, halls: Array<HallRow>, 
/**
 * 旧称。
 */
pastNames: Array<VenueNameRow>, 
/**
 * 「基本情報」の行 (所在・収容人数・別名)。曲の `fact_rows` と同じ形。
 */
factRows: Array<ProfileRow>, events: Array<Ref>, shows: Array<ShowSummary>, app: AppOpen, seo: SeoBlock, };
