// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 旧称の 1 行 (命名権で会場名が変わる)。
 */
export type VenueNameRow = { name: string, startDate: string | null, endDate: string | null, };
