// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ref } from "./Ref";

/**
 * 会場一覧の 1 行。
 */
export type VenueListItem = { ref: Ref, prefecture: string | null, city: string | null, capacity: number | null, showCount: number, };
