// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * CV の履歴 1 行。
 */
export type VoiceActorRow = { name: string, startDate: string | null, endDate: string | null, isCurrent: boolean, note: string | null, };
