// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 年ごとの公演数の棒 1 本。
 */
export type YearBar = { 
/**
 * `2026`。
 */
year: string, 
/**
 * 棒の下に置く短い年 (`26`)。
 */
short: string, value: number, 
/**
 * 最大の年に対する千分率。
 */
sharePermille: number, 
/**
 * 今年か、それより先の年 (予定を含む)。
 */
isPlanned: boolean, };
