// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventListItem } from "./EventListItem";
import type { NavLink } from "./NavLink";

/**
 * 年ごとのまとまり。
 */
export type YearGroup = { year: string, events: Array<EventListItem>, 
/**
 * この束の続き (ハブでは「開催済みをすべて見る」、年の一覧では 1 つ前の年)。
 * 一覧が途中で切れていることを行の下で言うための 1 本。
 */
more: NavLink | null, };
