// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventListItem } from "./EventListItem";
import type { MonthSpan } from "./MonthSpan";

/**
 * 年ごとのまとまり。
 */
export type YearGroup = { year: string, events: Array<EventListItem>, 
/**
 * `events` を月で区切った区間 (並び順どおり)。各区間の件数を足すと `events` の数。
 */
months: Array<MonthSpan>, };
