// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventListItem } from "./EventListItem";

/**
 * 年ごとのまとまり。
 */
export type YearGroup = { year: string, events: Array<EventListItem>, };
